---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryde-qa-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryde-qa-worker
  template:
    metadata:
      labels:
        app: ryde-qa-worker
    spec:
      containers:
        - name: worker
          command: ['npm', 'run', 'worker']
          image: volume7/backend:__IMAGE_TAG__-qa
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: ryde-qa
            - configMapRef:
                name: ryde-qa
      imagePullSecrets:
        - name: docker-hub
