/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUnauthorizedRouteImport } from './routes/_auth/unauthorized'
import { Route as AuthNotFoundRouteImport } from './routes/_auth/not-found'
import { Route as AuthErrorRouteImport } from './routes/_auth/error'
import { Route as AuthExampleRouteRouteImport } from './routes/_auth/example/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as AuthExampleUploadIndexRouteImport } from './routes/_auth/example/upload/index'
import { Route as AuthExampleOrdersIndexRouteImport } from './routes/_auth/example/orders/index'
import { Route as AuthExampleMyUploadsIndexRouteImport } from './routes/_auth/example/my-uploads/index'
import { Route as AuthExampleKitchenSinkIndexRouteImport } from './routes/_auth/example/kitchen-sink/index'
import { Route as AuthExampleClientsIndexRouteImport } from './routes/_auth/example/clients/index'
import { Route as AuthAdminUsersIndexRouteImport } from './routes/_auth/admin/users/index'
import { Route as AuthExampleOrdersNewRouteImport } from './routes/_auth/example/orders/new'
import { Route as AuthExampleOrdersOrderIdRouteImport } from './routes/_auth/example/orders/$orderId'
import { Route as AuthExampleMyUploadsUploadIdRouteImport } from './routes/_auth/example/my-uploads/$uploadId'
import { Route as AuthExampleClientsNewRouteImport } from './routes/_auth/example/clients/new'
import { Route as AuthExampleClientsClientIdRouteImport } from './routes/_auth/example/clients/$clientId'
import { Route as AuthAdminUsersCreateRouteImport } from './routes/_auth/admin/users/create'
import { Route as AuthAdminUsersUserIdRouteImport } from './routes/_auth/admin/users/$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthNotFoundRoute = AuthNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthExampleRouteRoute = AuthExampleRouteRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthExampleUploadIndexRoute = AuthExampleUploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => AuthExampleRouteRoute,
} as any)
const AuthExampleOrdersIndexRoute = AuthExampleOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthExampleRouteRoute,
} as any)
const AuthExampleMyUploadsIndexRoute =
  AuthExampleMyUploadsIndexRouteImport.update({
    id: '/my-uploads/',
    path: '/my-uploads/',
    getParentRoute: () => AuthExampleRouteRoute,
  } as any)
const AuthExampleKitchenSinkIndexRoute =
  AuthExampleKitchenSinkIndexRouteImport.update({
    id: '/kitchen-sink/',
    path: '/kitchen-sink/',
    getParentRoute: () => AuthExampleRouteRoute,
  } as any)
const AuthExampleClientsIndexRoute = AuthExampleClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthExampleRouteRoute,
} as any)
const AuthAdminUsersIndexRoute = AuthAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthExampleOrdersNewRoute = AuthExampleOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AuthExampleRouteRoute,
} as any)
const AuthExampleOrdersOrderIdRoute =
  AuthExampleOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthExampleRouteRoute,
  } as any)
const AuthExampleMyUploadsUploadIdRoute =
  AuthExampleMyUploadsUploadIdRouteImport.update({
    id: '/my-uploads/$uploadId',
    path: '/my-uploads/$uploadId',
    getParentRoute: () => AuthExampleRouteRoute,
  } as any)
const AuthExampleClientsNewRoute = AuthExampleClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthExampleRouteRoute,
} as any)
const AuthExampleClientsClientIdRoute =
  AuthExampleClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthExampleRouteRoute,
  } as any)
const AuthAdminUsersCreateRoute = AuthAdminUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminUsersUserIdRoute = AuthAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/example': typeof AuthExampleRouteRouteWithChildren
  '/error': typeof AuthErrorRoute
  '/not-found': typeof AuthNotFoundRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/': typeof AuthIndexRoute
  '/admin/users/$userId': typeof AuthAdminUsersUserIdRoute
  '/admin/users/create': typeof AuthAdminUsersCreateRoute
  '/example/clients/$clientId': typeof AuthExampleClientsClientIdRoute
  '/example/clients/new': typeof AuthExampleClientsNewRoute
  '/example/my-uploads/$uploadId': typeof AuthExampleMyUploadsUploadIdRoute
  '/example/orders/$orderId': typeof AuthExampleOrdersOrderIdRoute
  '/example/orders/new': typeof AuthExampleOrdersNewRoute
  '/admin/users': typeof AuthAdminUsersIndexRoute
  '/example/clients': typeof AuthExampleClientsIndexRoute
  '/example/kitchen-sink': typeof AuthExampleKitchenSinkIndexRoute
  '/example/my-uploads': typeof AuthExampleMyUploadsIndexRoute
  '/example/orders': typeof AuthExampleOrdersIndexRoute
  '/example/upload': typeof AuthExampleUploadIndexRoute
}
export interface FileRoutesByTo {
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/example': typeof AuthExampleRouteRouteWithChildren
  '/error': typeof AuthErrorRoute
  '/not-found': typeof AuthNotFoundRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/': typeof AuthIndexRoute
  '/admin/users/$userId': typeof AuthAdminUsersUserIdRoute
  '/admin/users/create': typeof AuthAdminUsersCreateRoute
  '/example/clients/$clientId': typeof AuthExampleClientsClientIdRoute
  '/example/clients/new': typeof AuthExampleClientsNewRoute
  '/example/my-uploads/$uploadId': typeof AuthExampleMyUploadsUploadIdRoute
  '/example/orders/$orderId': typeof AuthExampleOrdersOrderIdRoute
  '/example/orders/new': typeof AuthExampleOrdersNewRoute
  '/admin/users': typeof AuthAdminUsersIndexRoute
  '/example/clients': typeof AuthExampleClientsIndexRoute
  '/example/kitchen-sink': typeof AuthExampleKitchenSinkIndexRoute
  '/example/my-uploads': typeof AuthExampleMyUploadsIndexRoute
  '/example/orders': typeof AuthExampleOrdersIndexRoute
  '/example/upload': typeof AuthExampleUploadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/example': typeof AuthExampleRouteRouteWithChildren
  '/_auth/error': typeof AuthErrorRoute
  '/_auth/not-found': typeof AuthNotFoundRoute
  '/_auth/unauthorized': typeof AuthUnauthorizedRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin/users/$userId': typeof AuthAdminUsersUserIdRoute
  '/_auth/admin/users/create': typeof AuthAdminUsersCreateRoute
  '/_auth/example/clients/$clientId': typeof AuthExampleClientsClientIdRoute
  '/_auth/example/clients/new': typeof AuthExampleClientsNewRoute
  '/_auth/example/my-uploads/$uploadId': typeof AuthExampleMyUploadsUploadIdRoute
  '/_auth/example/orders/$orderId': typeof AuthExampleOrdersOrderIdRoute
  '/_auth/example/orders/new': typeof AuthExampleOrdersNewRoute
  '/_auth/admin/users/': typeof AuthAdminUsersIndexRoute
  '/_auth/example/clients/': typeof AuthExampleClientsIndexRoute
  '/_auth/example/kitchen-sink/': typeof AuthExampleKitchenSinkIndexRoute
  '/_auth/example/my-uploads/': typeof AuthExampleMyUploadsIndexRoute
  '/_auth/example/orders/': typeof AuthExampleOrdersIndexRoute
  '/_auth/example/upload/': typeof AuthExampleUploadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/join'
    | '/login'
    | '/admin'
    | '/example'
    | '/error'
    | '/not-found'
    | '/unauthorized'
    | '/'
    | '/admin/users/$userId'
    | '/admin/users/create'
    | '/example/clients/$clientId'
    | '/example/clients/new'
    | '/example/my-uploads/$uploadId'
    | '/example/orders/$orderId'
    | '/example/orders/new'
    | '/admin/users'
    | '/example/clients'
    | '/example/kitchen-sink'
    | '/example/my-uploads'
    | '/example/orders'
    | '/example/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/join'
    | '/login'
    | '/admin'
    | '/example'
    | '/error'
    | '/not-found'
    | '/unauthorized'
    | '/'
    | '/admin/users/$userId'
    | '/admin/users/create'
    | '/example/clients/$clientId'
    | '/example/clients/new'
    | '/example/my-uploads/$uploadId'
    | '/example/orders/$orderId'
    | '/example/orders/new'
    | '/admin/users'
    | '/example/clients'
    | '/example/kitchen-sink'
    | '/example/my-uploads'
    | '/example/orders'
    | '/example/upload'
  id:
    | '__root__'
    | '/_auth'
    | '/join'
    | '/login'
    | '/_auth/admin'
    | '/_auth/example'
    | '/_auth/error'
    | '/_auth/not-found'
    | '/_auth/unauthorized'
    | '/_auth/'
    | '/_auth/admin/users/$userId'
    | '/_auth/admin/users/create'
    | '/_auth/example/clients/$clientId'
    | '/_auth/example/clients/new'
    | '/_auth/example/my-uploads/$uploadId'
    | '/_auth/example/orders/$orderId'
    | '/_auth/example/orders/new'
    | '/_auth/admin/users/'
    | '/_auth/example/clients/'
    | '/_auth/example/kitchen-sink/'
    | '/_auth/example/my-uploads/'
    | '/_auth/example/orders/'
    | '/_auth/example/upload/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/unauthorized': {
      id: '/_auth/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/not-found': {
      id: '/_auth/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof AuthNotFoundRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/error': {
      id: '/_auth/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/example': {
      id: '/_auth/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof AuthExampleRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/example/upload/': {
      id: '/_auth/example/upload/'
      path: '/upload'
      fullPath: '/example/upload'
      preLoaderRoute: typeof AuthExampleUploadIndexRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/orders/': {
      id: '/_auth/example/orders/'
      path: '/orders'
      fullPath: '/example/orders'
      preLoaderRoute: typeof AuthExampleOrdersIndexRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/my-uploads/': {
      id: '/_auth/example/my-uploads/'
      path: '/my-uploads'
      fullPath: '/example/my-uploads'
      preLoaderRoute: typeof AuthExampleMyUploadsIndexRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/kitchen-sink/': {
      id: '/_auth/example/kitchen-sink/'
      path: '/kitchen-sink'
      fullPath: '/example/kitchen-sink'
      preLoaderRoute: typeof AuthExampleKitchenSinkIndexRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/clients/': {
      id: '/_auth/example/clients/'
      path: '/clients'
      fullPath: '/example/clients'
      preLoaderRoute: typeof AuthExampleClientsIndexRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/admin/users/': {
      id: '/_auth/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/example/orders/new': {
      id: '/_auth/example/orders/new'
      path: '/orders/new'
      fullPath: '/example/orders/new'
      preLoaderRoute: typeof AuthExampleOrdersNewRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/orders/$orderId': {
      id: '/_auth/example/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/example/orders/$orderId'
      preLoaderRoute: typeof AuthExampleOrdersOrderIdRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/my-uploads/$uploadId': {
      id: '/_auth/example/my-uploads/$uploadId'
      path: '/my-uploads/$uploadId'
      fullPath: '/example/my-uploads/$uploadId'
      preLoaderRoute: typeof AuthExampleMyUploadsUploadIdRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/clients/new': {
      id: '/_auth/example/clients/new'
      path: '/clients/new'
      fullPath: '/example/clients/new'
      preLoaderRoute: typeof AuthExampleClientsNewRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/clients/$clientId': {
      id: '/_auth/example/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/example/clients/$clientId'
      preLoaderRoute: typeof AuthExampleClientsClientIdRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/admin/users/create': {
      id: '/_auth/admin/users/create'
      path: '/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AuthAdminUsersCreateRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/users/$userId': {
      id: '/_auth/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthAdminUsersUserIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
  }
}

interface AuthAdminRouteRouteChildren {
  AuthAdminUsersUserIdRoute: typeof AuthAdminUsersUserIdRoute
  AuthAdminUsersCreateRoute: typeof AuthAdminUsersCreateRoute
  AuthAdminUsersIndexRoute: typeof AuthAdminUsersIndexRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminUsersUserIdRoute: AuthAdminUsersUserIdRoute,
  AuthAdminUsersCreateRoute: AuthAdminUsersCreateRoute,
  AuthAdminUsersIndexRoute: AuthAdminUsersIndexRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthExampleRouteRouteChildren {
  AuthExampleClientsClientIdRoute: typeof AuthExampleClientsClientIdRoute
  AuthExampleClientsNewRoute: typeof AuthExampleClientsNewRoute
  AuthExampleMyUploadsUploadIdRoute: typeof AuthExampleMyUploadsUploadIdRoute
  AuthExampleOrdersOrderIdRoute: typeof AuthExampleOrdersOrderIdRoute
  AuthExampleOrdersNewRoute: typeof AuthExampleOrdersNewRoute
  AuthExampleClientsIndexRoute: typeof AuthExampleClientsIndexRoute
  AuthExampleKitchenSinkIndexRoute: typeof AuthExampleKitchenSinkIndexRoute
  AuthExampleMyUploadsIndexRoute: typeof AuthExampleMyUploadsIndexRoute
  AuthExampleOrdersIndexRoute: typeof AuthExampleOrdersIndexRoute
  AuthExampleUploadIndexRoute: typeof AuthExampleUploadIndexRoute
}

const AuthExampleRouteRouteChildren: AuthExampleRouteRouteChildren = {
  AuthExampleClientsClientIdRoute: AuthExampleClientsClientIdRoute,
  AuthExampleClientsNewRoute: AuthExampleClientsNewRoute,
  AuthExampleMyUploadsUploadIdRoute: AuthExampleMyUploadsUploadIdRoute,
  AuthExampleOrdersOrderIdRoute: AuthExampleOrdersOrderIdRoute,
  AuthExampleOrdersNewRoute: AuthExampleOrdersNewRoute,
  AuthExampleClientsIndexRoute: AuthExampleClientsIndexRoute,
  AuthExampleKitchenSinkIndexRoute: AuthExampleKitchenSinkIndexRoute,
  AuthExampleMyUploadsIndexRoute: AuthExampleMyUploadsIndexRoute,
  AuthExampleOrdersIndexRoute: AuthExampleOrdersIndexRoute,
  AuthExampleUploadIndexRoute: AuthExampleUploadIndexRoute,
}

const AuthExampleRouteRouteWithChildren =
  AuthExampleRouteRoute._addFileChildren(AuthExampleRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthExampleRouteRoute: typeof AuthExampleRouteRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  AuthNotFoundRoute: typeof AuthNotFoundRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthExampleRouteRoute: AuthExampleRouteRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  AuthNotFoundRoute: AuthNotFoundRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
