/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUnauthorizedRouteImport } from './routes/_auth/unauthorized'
import { Route as AuthNotFoundRouteImport } from './routes/_auth/not-found'
import { Route as AuthErrorRouteImport } from './routes/_auth/error'
import { Route as AuthExampleRouteRouteImport } from './routes/_auth/example/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as AuthAdminUsersRouteRouteImport } from './routes/_auth/admin/users/route'
import { Route as AuthExampleUploadIndexRouteImport } from './routes/_auth/example/upload/index'
import { Route as AuthExampleOrdersIndexRouteImport } from './routes/_auth/example/orders/index'
import { Route as AuthExampleMyUploadsIndexRouteImport } from './routes/_auth/example/my-uploads/index'
import { Route as AuthExampleKitchenSinkIndexRouteImport } from './routes/_auth/example/kitchen-sink/index'
import { Route as AuthExampleClientsIndexRouteImport } from './routes/_auth/example/clients/index'
import { Route as AuthAdminUsersIndexRouteImport } from './routes/_auth/admin/users/index'
import { Route as AuthAdminImportsIndexRouteImport } from './routes/_auth/admin/imports/index'
import { Route as AuthExampleOrdersNewRouteImport } from './routes/_auth/example/orders/new'
import { Route as AuthExampleOrdersOrderIdRouteImport } from './routes/_auth/example/orders/$orderId'
import { Route as AuthExampleMyUploadsUploadIdRouteImport } from './routes/_auth/example/my-uploads/$uploadId'
import { Route as AuthExampleClientsNewRouteImport } from './routes/_auth/example/clients/new'
import { Route as AuthExampleClientsClientIdRouteImport } from './routes/_auth/example/clients/$clientId'
import { Route as AuthAdminUsersCreateRouteImport } from './routes/_auth/admin/users/create'
import { Route as AuthAdminUsersUserIdRouteImport } from './routes/_auth/admin/users/$userId'
import { Route as AuthAdminImportsSellOutRabbaIndexRouteImport } from './routes/_auth/admin/imports/sell-out-rabba/index'
import { Route as AuthAdminImportsSellInTargetsIndexRouteImport } from './routes/_auth/admin/imports/sell-in-targets/index'
import { Route as AuthAdminImportsSellInOrdersIndexRouteImport } from './routes/_auth/admin/imports/sell-in-orders/index'
import { Route as AuthAdminImportsSellInOrdersConfirmedIndexRouteImport } from './routes/_auth/admin/imports/sell-in-orders-confirmed/index'
import { Route as AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRouteImport } from './routes/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/index'
import { Route as AuthAdminImportsProductsIndexRouteImport } from './routes/_auth/admin/imports/products/index'
import { Route as AuthAdminImportsProductFormatsIndexRouteImport } from './routes/_auth/admin/imports/product-formats/index'
import { Route as AuthAdminImportsCustomersIndexRouteImport } from './routes/_auth/admin/imports/customers/index'
import { Route as AuthAdminImportsAmazonOrdersIndexRouteImport } from './routes/_auth/admin/imports/amazon-orders/index'
import { Route as AuthAdminImportsAmazonBundlesIndexRouteImport } from './routes/_auth/admin/imports/amazon-bundles/index'
import { Route as AuthAdminImportsSellOutRabbaReportIdRouteImport } from './routes/_auth/admin/imports/sell-out-rabba/$reportId'
import { Route as AuthAdminImportsSellInTargetsReportIdRouteImport } from './routes/_auth/admin/imports/sell-in-targets/$reportId'
import { Route as AuthAdminImportsSellInOrdersReportIdRouteImport } from './routes/_auth/admin/imports/sell-in-orders/$reportId'
import { Route as AuthAdminImportsSellInOrdersConfirmedReportIdRouteImport } from './routes/_auth/admin/imports/sell-in-orders-confirmed/$reportId'
import { Route as AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRouteImport } from './routes/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId'
import { Route as AuthAdminImportsCustomersReportIdRouteImport } from './routes/_auth/admin/imports/customers/$reportId'
import { Route as AuthAdminImportsAmazonOrdersReportIdRouteImport } from './routes/_auth/admin/imports/amazon-orders/$reportId'
import { Route as AuthAdminImportsAmazonBundlesReportIdRouteImport } from './routes/_auth/admin/imports/amazon-bundles/$reportId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthNotFoundRoute = AuthNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthExampleRouteRoute = AuthExampleRouteRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminUsersRouteRoute = AuthAdminUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthExampleUploadIndexRoute = AuthExampleUploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => AuthExampleRouteRoute,
} as any)
const AuthExampleOrdersIndexRoute = AuthExampleOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthExampleRouteRoute,
} as any)
const AuthExampleMyUploadsIndexRoute =
  AuthExampleMyUploadsIndexRouteImport.update({
    id: '/my-uploads/',
    path: '/my-uploads/',
    getParentRoute: () => AuthExampleRouteRoute,
  } as any)
const AuthExampleKitchenSinkIndexRoute =
  AuthExampleKitchenSinkIndexRouteImport.update({
    id: '/kitchen-sink/',
    path: '/kitchen-sink/',
    getParentRoute: () => AuthExampleRouteRoute,
  } as any)
const AuthExampleClientsIndexRoute = AuthExampleClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthExampleRouteRoute,
} as any)
const AuthAdminUsersIndexRoute = AuthAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminUsersRouteRoute,
} as any)
const AuthAdminImportsIndexRoute = AuthAdminImportsIndexRouteImport.update({
  id: '/imports/',
  path: '/imports/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthExampleOrdersNewRoute = AuthExampleOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AuthExampleRouteRoute,
} as any)
const AuthExampleOrdersOrderIdRoute =
  AuthExampleOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthExampleRouteRoute,
  } as any)
const AuthExampleMyUploadsUploadIdRoute =
  AuthExampleMyUploadsUploadIdRouteImport.update({
    id: '/my-uploads/$uploadId',
    path: '/my-uploads/$uploadId',
    getParentRoute: () => AuthExampleRouteRoute,
  } as any)
const AuthExampleClientsNewRoute = AuthExampleClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthExampleRouteRoute,
} as any)
const AuthExampleClientsClientIdRoute =
  AuthExampleClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthExampleRouteRoute,
  } as any)
const AuthAdminUsersCreateRoute = AuthAdminUsersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthAdminUsersRouteRoute,
} as any)
const AuthAdminUsersUserIdRoute = AuthAdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AuthAdminUsersRouteRoute,
} as any)
const AuthAdminImportsSellOutRabbaIndexRoute =
  AuthAdminImportsSellOutRabbaIndexRouteImport.update({
    id: '/imports/sell-out-rabba/',
    path: '/imports/sell-out-rabba/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInTargetsIndexRoute =
  AuthAdminImportsSellInTargetsIndexRouteImport.update({
    id: '/imports/sell-in-targets/',
    path: '/imports/sell-in-targets/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInOrdersIndexRoute =
  AuthAdminImportsSellInOrdersIndexRouteImport.update({
    id: '/imports/sell-in-orders/',
    path: '/imports/sell-in-orders/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInOrdersConfirmedIndexRoute =
  AuthAdminImportsSellInOrdersConfirmedIndexRouteImport.update({
    id: '/imports/sell-in-orders-confirmed/',
    path: '/imports/sell-in-orders-confirmed/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute =
  AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRouteImport.update({
    id: '/imports/sell-in-orders-confirmed-7-eleven/',
    path: '/imports/sell-in-orders-confirmed-7-eleven/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsProductsIndexRoute =
  AuthAdminImportsProductsIndexRouteImport.update({
    id: '/imports/products/',
    path: '/imports/products/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsProductFormatsIndexRoute =
  AuthAdminImportsProductFormatsIndexRouteImport.update({
    id: '/imports/product-formats/',
    path: '/imports/product-formats/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsCustomersIndexRoute =
  AuthAdminImportsCustomersIndexRouteImport.update({
    id: '/imports/customers/',
    path: '/imports/customers/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsAmazonOrdersIndexRoute =
  AuthAdminImportsAmazonOrdersIndexRouteImport.update({
    id: '/imports/amazon-orders/',
    path: '/imports/amazon-orders/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsAmazonBundlesIndexRoute =
  AuthAdminImportsAmazonBundlesIndexRouteImport.update({
    id: '/imports/amazon-bundles/',
    path: '/imports/amazon-bundles/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutRabbaReportIdRoute =
  AuthAdminImportsSellOutRabbaReportIdRouteImport.update({
    id: '/imports/sell-out-rabba/$reportId',
    path: '/imports/sell-out-rabba/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInTargetsReportIdRoute =
  AuthAdminImportsSellInTargetsReportIdRouteImport.update({
    id: '/imports/sell-in-targets/$reportId',
    path: '/imports/sell-in-targets/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInOrdersReportIdRoute =
  AuthAdminImportsSellInOrdersReportIdRouteImport.update({
    id: '/imports/sell-in-orders/$reportId',
    path: '/imports/sell-in-orders/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInOrdersConfirmedReportIdRoute =
  AuthAdminImportsSellInOrdersConfirmedReportIdRouteImport.update({
    id: '/imports/sell-in-orders-confirmed/$reportId',
    path: '/imports/sell-in-orders-confirmed/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute =
  AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRouteImport.update({
    id: '/imports/sell-in-orders-confirmed-7-eleven/$reportId',
    path: '/imports/sell-in-orders-confirmed-7-eleven/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsCustomersReportIdRoute =
  AuthAdminImportsCustomersReportIdRouteImport.update({
    id: '/imports/customers/$reportId',
    path: '/imports/customers/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsAmazonOrdersReportIdRoute =
  AuthAdminImportsAmazonOrdersReportIdRouteImport.update({
    id: '/imports/amazon-orders/$reportId',
    path: '/imports/amazon-orders/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsAmazonBundlesReportIdRoute =
  AuthAdminImportsAmazonBundlesReportIdRouteImport.update({
    id: '/imports/amazon-bundles/$reportId',
    path: '/imports/amazon-bundles/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/example': typeof AuthExampleRouteRouteWithChildren
  '/error': typeof AuthErrorRoute
  '/not-found': typeof AuthNotFoundRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/': typeof AuthIndexRoute
  '/admin/users': typeof AuthAdminUsersRouteRouteWithChildren
  '/admin/users/$userId': typeof AuthAdminUsersUserIdRoute
  '/admin/users/create': typeof AuthAdminUsersCreateRoute
  '/example/clients/$clientId': typeof AuthExampleClientsClientIdRoute
  '/example/clients/new': typeof AuthExampleClientsNewRoute
  '/example/my-uploads/$uploadId': typeof AuthExampleMyUploadsUploadIdRoute
  '/example/orders/$orderId': typeof AuthExampleOrdersOrderIdRoute
  '/example/orders/new': typeof AuthExampleOrdersNewRoute
  '/admin/imports': typeof AuthAdminImportsIndexRoute
  '/admin/users/': typeof AuthAdminUsersIndexRoute
  '/example/clients': typeof AuthExampleClientsIndexRoute
  '/example/kitchen-sink': typeof AuthExampleKitchenSinkIndexRoute
  '/example/my-uploads': typeof AuthExampleMyUploadsIndexRoute
  '/example/orders': typeof AuthExampleOrdersIndexRoute
  '/example/upload': typeof AuthExampleUploadIndexRoute
  '/admin/imports/amazon-bundles/$reportId': typeof AuthAdminImportsAmazonBundlesReportIdRoute
  '/admin/imports/amazon-orders/$reportId': typeof AuthAdminImportsAmazonOrdersReportIdRoute
  '/admin/imports/customers/$reportId': typeof AuthAdminImportsCustomersReportIdRoute
  '/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId': typeof AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute
  '/admin/imports/sell-in-orders-confirmed/$reportId': typeof AuthAdminImportsSellInOrdersConfirmedReportIdRoute
  '/admin/imports/sell-in-orders/$reportId': typeof AuthAdminImportsSellInOrdersReportIdRoute
  '/admin/imports/sell-in-targets/$reportId': typeof AuthAdminImportsSellInTargetsReportIdRoute
  '/admin/imports/sell-out-rabba/$reportId': typeof AuthAdminImportsSellOutRabbaReportIdRoute
  '/admin/imports/amazon-bundles': typeof AuthAdminImportsAmazonBundlesIndexRoute
  '/admin/imports/amazon-orders': typeof AuthAdminImportsAmazonOrdersIndexRoute
  '/admin/imports/customers': typeof AuthAdminImportsCustomersIndexRoute
  '/admin/imports/product-formats': typeof AuthAdminImportsProductFormatsIndexRoute
  '/admin/imports/products': typeof AuthAdminImportsProductsIndexRoute
  '/admin/imports/sell-in-orders-confirmed-7-eleven': typeof AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute
  '/admin/imports/sell-in-orders-confirmed': typeof AuthAdminImportsSellInOrdersConfirmedIndexRoute
  '/admin/imports/sell-in-orders': typeof AuthAdminImportsSellInOrdersIndexRoute
  '/admin/imports/sell-in-targets': typeof AuthAdminImportsSellInTargetsIndexRoute
  '/admin/imports/sell-out-rabba': typeof AuthAdminImportsSellOutRabbaIndexRoute
}
export interface FileRoutesByTo {
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/example': typeof AuthExampleRouteRouteWithChildren
  '/error': typeof AuthErrorRoute
  '/not-found': typeof AuthNotFoundRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/': typeof AuthIndexRoute
  '/admin/users/$userId': typeof AuthAdminUsersUserIdRoute
  '/admin/users/create': typeof AuthAdminUsersCreateRoute
  '/example/clients/$clientId': typeof AuthExampleClientsClientIdRoute
  '/example/clients/new': typeof AuthExampleClientsNewRoute
  '/example/my-uploads/$uploadId': typeof AuthExampleMyUploadsUploadIdRoute
  '/example/orders/$orderId': typeof AuthExampleOrdersOrderIdRoute
  '/example/orders/new': typeof AuthExampleOrdersNewRoute
  '/admin/imports': typeof AuthAdminImportsIndexRoute
  '/admin/users': typeof AuthAdminUsersIndexRoute
  '/example/clients': typeof AuthExampleClientsIndexRoute
  '/example/kitchen-sink': typeof AuthExampleKitchenSinkIndexRoute
  '/example/my-uploads': typeof AuthExampleMyUploadsIndexRoute
  '/example/orders': typeof AuthExampleOrdersIndexRoute
  '/example/upload': typeof AuthExampleUploadIndexRoute
  '/admin/imports/amazon-bundles/$reportId': typeof AuthAdminImportsAmazonBundlesReportIdRoute
  '/admin/imports/amazon-orders/$reportId': typeof AuthAdminImportsAmazonOrdersReportIdRoute
  '/admin/imports/customers/$reportId': typeof AuthAdminImportsCustomersReportIdRoute
  '/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId': typeof AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute
  '/admin/imports/sell-in-orders-confirmed/$reportId': typeof AuthAdminImportsSellInOrdersConfirmedReportIdRoute
  '/admin/imports/sell-in-orders/$reportId': typeof AuthAdminImportsSellInOrdersReportIdRoute
  '/admin/imports/sell-in-targets/$reportId': typeof AuthAdminImportsSellInTargetsReportIdRoute
  '/admin/imports/sell-out-rabba/$reportId': typeof AuthAdminImportsSellOutRabbaReportIdRoute
  '/admin/imports/amazon-bundles': typeof AuthAdminImportsAmazonBundlesIndexRoute
  '/admin/imports/amazon-orders': typeof AuthAdminImportsAmazonOrdersIndexRoute
  '/admin/imports/customers': typeof AuthAdminImportsCustomersIndexRoute
  '/admin/imports/product-formats': typeof AuthAdminImportsProductFormatsIndexRoute
  '/admin/imports/products': typeof AuthAdminImportsProductsIndexRoute
  '/admin/imports/sell-in-orders-confirmed-7-eleven': typeof AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute
  '/admin/imports/sell-in-orders-confirmed': typeof AuthAdminImportsSellInOrdersConfirmedIndexRoute
  '/admin/imports/sell-in-orders': typeof AuthAdminImportsSellInOrdersIndexRoute
  '/admin/imports/sell-in-targets': typeof AuthAdminImportsSellInTargetsIndexRoute
  '/admin/imports/sell-out-rabba': typeof AuthAdminImportsSellOutRabbaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/example': typeof AuthExampleRouteRouteWithChildren
  '/_auth/error': typeof AuthErrorRoute
  '/_auth/not-found': typeof AuthNotFoundRoute
  '/_auth/unauthorized': typeof AuthUnauthorizedRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin/users': typeof AuthAdminUsersRouteRouteWithChildren
  '/_auth/admin/users/$userId': typeof AuthAdminUsersUserIdRoute
  '/_auth/admin/users/create': typeof AuthAdminUsersCreateRoute
  '/_auth/example/clients/$clientId': typeof AuthExampleClientsClientIdRoute
  '/_auth/example/clients/new': typeof AuthExampleClientsNewRoute
  '/_auth/example/my-uploads/$uploadId': typeof AuthExampleMyUploadsUploadIdRoute
  '/_auth/example/orders/$orderId': typeof AuthExampleOrdersOrderIdRoute
  '/_auth/example/orders/new': typeof AuthExampleOrdersNewRoute
  '/_auth/admin/imports/': typeof AuthAdminImportsIndexRoute
  '/_auth/admin/users/': typeof AuthAdminUsersIndexRoute
  '/_auth/example/clients/': typeof AuthExampleClientsIndexRoute
  '/_auth/example/kitchen-sink/': typeof AuthExampleKitchenSinkIndexRoute
  '/_auth/example/my-uploads/': typeof AuthExampleMyUploadsIndexRoute
  '/_auth/example/orders/': typeof AuthExampleOrdersIndexRoute
  '/_auth/example/upload/': typeof AuthExampleUploadIndexRoute
  '/_auth/admin/imports/amazon-bundles/$reportId': typeof AuthAdminImportsAmazonBundlesReportIdRoute
  '/_auth/admin/imports/amazon-orders/$reportId': typeof AuthAdminImportsAmazonOrdersReportIdRoute
  '/_auth/admin/imports/customers/$reportId': typeof AuthAdminImportsCustomersReportIdRoute
  '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId': typeof AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute
  '/_auth/admin/imports/sell-in-orders-confirmed/$reportId': typeof AuthAdminImportsSellInOrdersConfirmedReportIdRoute
  '/_auth/admin/imports/sell-in-orders/$reportId': typeof AuthAdminImportsSellInOrdersReportIdRoute
  '/_auth/admin/imports/sell-in-targets/$reportId': typeof AuthAdminImportsSellInTargetsReportIdRoute
  '/_auth/admin/imports/sell-out-rabba/$reportId': typeof AuthAdminImportsSellOutRabbaReportIdRoute
  '/_auth/admin/imports/amazon-bundles/': typeof AuthAdminImportsAmazonBundlesIndexRoute
  '/_auth/admin/imports/amazon-orders/': typeof AuthAdminImportsAmazonOrdersIndexRoute
  '/_auth/admin/imports/customers/': typeof AuthAdminImportsCustomersIndexRoute
  '/_auth/admin/imports/product-formats/': typeof AuthAdminImportsProductFormatsIndexRoute
  '/_auth/admin/imports/products/': typeof AuthAdminImportsProductsIndexRoute
  '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/': typeof AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute
  '/_auth/admin/imports/sell-in-orders-confirmed/': typeof AuthAdminImportsSellInOrdersConfirmedIndexRoute
  '/_auth/admin/imports/sell-in-orders/': typeof AuthAdminImportsSellInOrdersIndexRoute
  '/_auth/admin/imports/sell-in-targets/': typeof AuthAdminImportsSellInTargetsIndexRoute
  '/_auth/admin/imports/sell-out-rabba/': typeof AuthAdminImportsSellOutRabbaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/join'
    | '/login'
    | '/admin'
    | '/example'
    | '/error'
    | '/not-found'
    | '/unauthorized'
    | '/'
    | '/admin/users'
    | '/admin/users/$userId'
    | '/admin/users/create'
    | '/example/clients/$clientId'
    | '/example/clients/new'
    | '/example/my-uploads/$uploadId'
    | '/example/orders/$orderId'
    | '/example/orders/new'
    | '/admin/imports'
    | '/admin/users/'
    | '/example/clients'
    | '/example/kitchen-sink'
    | '/example/my-uploads'
    | '/example/orders'
    | '/example/upload'
    | '/admin/imports/amazon-bundles/$reportId'
    | '/admin/imports/amazon-orders/$reportId'
    | '/admin/imports/customers/$reportId'
    | '/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId'
    | '/admin/imports/sell-in-orders-confirmed/$reportId'
    | '/admin/imports/sell-in-orders/$reportId'
    | '/admin/imports/sell-in-targets/$reportId'
    | '/admin/imports/sell-out-rabba/$reportId'
    | '/admin/imports/amazon-bundles'
    | '/admin/imports/amazon-orders'
    | '/admin/imports/customers'
    | '/admin/imports/product-formats'
    | '/admin/imports/products'
    | '/admin/imports/sell-in-orders-confirmed-7-eleven'
    | '/admin/imports/sell-in-orders-confirmed'
    | '/admin/imports/sell-in-orders'
    | '/admin/imports/sell-in-targets'
    | '/admin/imports/sell-out-rabba'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/join'
    | '/login'
    | '/admin'
    | '/example'
    | '/error'
    | '/not-found'
    | '/unauthorized'
    | '/'
    | '/admin/users/$userId'
    | '/admin/users/create'
    | '/example/clients/$clientId'
    | '/example/clients/new'
    | '/example/my-uploads/$uploadId'
    | '/example/orders/$orderId'
    | '/example/orders/new'
    | '/admin/imports'
    | '/admin/users'
    | '/example/clients'
    | '/example/kitchen-sink'
    | '/example/my-uploads'
    | '/example/orders'
    | '/example/upload'
    | '/admin/imports/amazon-bundles/$reportId'
    | '/admin/imports/amazon-orders/$reportId'
    | '/admin/imports/customers/$reportId'
    | '/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId'
    | '/admin/imports/sell-in-orders-confirmed/$reportId'
    | '/admin/imports/sell-in-orders/$reportId'
    | '/admin/imports/sell-in-targets/$reportId'
    | '/admin/imports/sell-out-rabba/$reportId'
    | '/admin/imports/amazon-bundles'
    | '/admin/imports/amazon-orders'
    | '/admin/imports/customers'
    | '/admin/imports/product-formats'
    | '/admin/imports/products'
    | '/admin/imports/sell-in-orders-confirmed-7-eleven'
    | '/admin/imports/sell-in-orders-confirmed'
    | '/admin/imports/sell-in-orders'
    | '/admin/imports/sell-in-targets'
    | '/admin/imports/sell-out-rabba'
  id:
    | '__root__'
    | '/_auth'
    | '/join'
    | '/login'
    | '/_auth/admin'
    | '/_auth/example'
    | '/_auth/error'
    | '/_auth/not-found'
    | '/_auth/unauthorized'
    | '/_auth/'
    | '/_auth/admin/users'
    | '/_auth/admin/users/$userId'
    | '/_auth/admin/users/create'
    | '/_auth/example/clients/$clientId'
    | '/_auth/example/clients/new'
    | '/_auth/example/my-uploads/$uploadId'
    | '/_auth/example/orders/$orderId'
    | '/_auth/example/orders/new'
    | '/_auth/admin/imports/'
    | '/_auth/admin/users/'
    | '/_auth/example/clients/'
    | '/_auth/example/kitchen-sink/'
    | '/_auth/example/my-uploads/'
    | '/_auth/example/orders/'
    | '/_auth/example/upload/'
    | '/_auth/admin/imports/amazon-bundles/$reportId'
    | '/_auth/admin/imports/amazon-orders/$reportId'
    | '/_auth/admin/imports/customers/$reportId'
    | '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId'
    | '/_auth/admin/imports/sell-in-orders-confirmed/$reportId'
    | '/_auth/admin/imports/sell-in-orders/$reportId'
    | '/_auth/admin/imports/sell-in-targets/$reportId'
    | '/_auth/admin/imports/sell-out-rabba/$reportId'
    | '/_auth/admin/imports/amazon-bundles/'
    | '/_auth/admin/imports/amazon-orders/'
    | '/_auth/admin/imports/customers/'
    | '/_auth/admin/imports/product-formats/'
    | '/_auth/admin/imports/products/'
    | '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/'
    | '/_auth/admin/imports/sell-in-orders-confirmed/'
    | '/_auth/admin/imports/sell-in-orders/'
    | '/_auth/admin/imports/sell-in-targets/'
    | '/_auth/admin/imports/sell-out-rabba/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/unauthorized': {
      id: '/_auth/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/not-found': {
      id: '/_auth/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof AuthNotFoundRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/error': {
      id: '/_auth/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/example': {
      id: '/_auth/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof AuthExampleRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/example/upload/': {
      id: '/_auth/example/upload/'
      path: '/upload'
      fullPath: '/example/upload'
      preLoaderRoute: typeof AuthExampleUploadIndexRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/orders/': {
      id: '/_auth/example/orders/'
      path: '/orders'
      fullPath: '/example/orders'
      preLoaderRoute: typeof AuthExampleOrdersIndexRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/my-uploads/': {
      id: '/_auth/example/my-uploads/'
      path: '/my-uploads'
      fullPath: '/example/my-uploads'
      preLoaderRoute: typeof AuthExampleMyUploadsIndexRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/kitchen-sink/': {
      id: '/_auth/example/kitchen-sink/'
      path: '/kitchen-sink'
      fullPath: '/example/kitchen-sink'
      preLoaderRoute: typeof AuthExampleKitchenSinkIndexRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/clients/': {
      id: '/_auth/example/clients/'
      path: '/clients'
      fullPath: '/example/clients'
      preLoaderRoute: typeof AuthExampleClientsIndexRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/admin/users/': {
      id: '/_auth/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthAdminUsersIndexRouteImport
      parentRoute: typeof AuthAdminUsersRouteRoute
    }
    '/_auth/admin/imports/': {
      id: '/_auth/admin/imports/'
      path: '/imports'
      fullPath: '/admin/imports'
      preLoaderRoute: typeof AuthAdminImportsIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/example/orders/new': {
      id: '/_auth/example/orders/new'
      path: '/orders/new'
      fullPath: '/example/orders/new'
      preLoaderRoute: typeof AuthExampleOrdersNewRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/orders/$orderId': {
      id: '/_auth/example/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/example/orders/$orderId'
      preLoaderRoute: typeof AuthExampleOrdersOrderIdRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/my-uploads/$uploadId': {
      id: '/_auth/example/my-uploads/$uploadId'
      path: '/my-uploads/$uploadId'
      fullPath: '/example/my-uploads/$uploadId'
      preLoaderRoute: typeof AuthExampleMyUploadsUploadIdRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/clients/new': {
      id: '/_auth/example/clients/new'
      path: '/clients/new'
      fullPath: '/example/clients/new'
      preLoaderRoute: typeof AuthExampleClientsNewRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/example/clients/$clientId': {
      id: '/_auth/example/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/example/clients/$clientId'
      preLoaderRoute: typeof AuthExampleClientsClientIdRouteImport
      parentRoute: typeof AuthExampleRouteRoute
    }
    '/_auth/admin/users/create': {
      id: '/_auth/admin/users/create'
      path: '/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AuthAdminUsersCreateRouteImport
      parentRoute: typeof AuthAdminUsersRouteRoute
    }
    '/_auth/admin/users/$userId': {
      id: '/_auth/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthAdminUsersUserIdRouteImport
      parentRoute: typeof AuthAdminUsersRouteRoute
    }
    '/_auth/admin/imports/sell-out-rabba/': {
      id: '/_auth/admin/imports/sell-out-rabba/'
      path: '/imports/sell-out-rabba'
      fullPath: '/admin/imports/sell-out-rabba'
      preLoaderRoute: typeof AuthAdminImportsSellOutRabbaIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-targets/': {
      id: '/_auth/admin/imports/sell-in-targets/'
      path: '/imports/sell-in-targets'
      fullPath: '/admin/imports/sell-in-targets'
      preLoaderRoute: typeof AuthAdminImportsSellInTargetsIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-orders/': {
      id: '/_auth/admin/imports/sell-in-orders/'
      path: '/imports/sell-in-orders'
      fullPath: '/admin/imports/sell-in-orders'
      preLoaderRoute: typeof AuthAdminImportsSellInOrdersIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-orders-confirmed/': {
      id: '/_auth/admin/imports/sell-in-orders-confirmed/'
      path: '/imports/sell-in-orders-confirmed'
      fullPath: '/admin/imports/sell-in-orders-confirmed'
      preLoaderRoute: typeof AuthAdminImportsSellInOrdersConfirmedIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/': {
      id: '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/'
      path: '/imports/sell-in-orders-confirmed-7-eleven'
      fullPath: '/admin/imports/sell-in-orders-confirmed-7-eleven'
      preLoaderRoute: typeof AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/products/': {
      id: '/_auth/admin/imports/products/'
      path: '/imports/products'
      fullPath: '/admin/imports/products'
      preLoaderRoute: typeof AuthAdminImportsProductsIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/product-formats/': {
      id: '/_auth/admin/imports/product-formats/'
      path: '/imports/product-formats'
      fullPath: '/admin/imports/product-formats'
      preLoaderRoute: typeof AuthAdminImportsProductFormatsIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/customers/': {
      id: '/_auth/admin/imports/customers/'
      path: '/imports/customers'
      fullPath: '/admin/imports/customers'
      preLoaderRoute: typeof AuthAdminImportsCustomersIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/amazon-orders/': {
      id: '/_auth/admin/imports/amazon-orders/'
      path: '/imports/amazon-orders'
      fullPath: '/admin/imports/amazon-orders'
      preLoaderRoute: typeof AuthAdminImportsAmazonOrdersIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/amazon-bundles/': {
      id: '/_auth/admin/imports/amazon-bundles/'
      path: '/imports/amazon-bundles'
      fullPath: '/admin/imports/amazon-bundles'
      preLoaderRoute: typeof AuthAdminImportsAmazonBundlesIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-rabba/$reportId': {
      id: '/_auth/admin/imports/sell-out-rabba/$reportId'
      path: '/imports/sell-out-rabba/$reportId'
      fullPath: '/admin/imports/sell-out-rabba/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellOutRabbaReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-targets/$reportId': {
      id: '/_auth/admin/imports/sell-in-targets/$reportId'
      path: '/imports/sell-in-targets/$reportId'
      fullPath: '/admin/imports/sell-in-targets/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellInTargetsReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-orders/$reportId': {
      id: '/_auth/admin/imports/sell-in-orders/$reportId'
      path: '/imports/sell-in-orders/$reportId'
      fullPath: '/admin/imports/sell-in-orders/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellInOrdersReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-orders-confirmed/$reportId': {
      id: '/_auth/admin/imports/sell-in-orders-confirmed/$reportId'
      path: '/imports/sell-in-orders-confirmed/$reportId'
      fullPath: '/admin/imports/sell-in-orders-confirmed/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellInOrdersConfirmedReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId': {
      id: '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId'
      path: '/imports/sell-in-orders-confirmed-7-eleven/$reportId'
      fullPath: '/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/customers/$reportId': {
      id: '/_auth/admin/imports/customers/$reportId'
      path: '/imports/customers/$reportId'
      fullPath: '/admin/imports/customers/$reportId'
      preLoaderRoute: typeof AuthAdminImportsCustomersReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/amazon-orders/$reportId': {
      id: '/_auth/admin/imports/amazon-orders/$reportId'
      path: '/imports/amazon-orders/$reportId'
      fullPath: '/admin/imports/amazon-orders/$reportId'
      preLoaderRoute: typeof AuthAdminImportsAmazonOrdersReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/amazon-bundles/$reportId': {
      id: '/_auth/admin/imports/amazon-bundles/$reportId'
      path: '/imports/amazon-bundles/$reportId'
      fullPath: '/admin/imports/amazon-bundles/$reportId'
      preLoaderRoute: typeof AuthAdminImportsAmazonBundlesReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
  }
}

interface AuthAdminUsersRouteRouteChildren {
  AuthAdminUsersUserIdRoute: typeof AuthAdminUsersUserIdRoute
  AuthAdminUsersCreateRoute: typeof AuthAdminUsersCreateRoute
  AuthAdminUsersIndexRoute: typeof AuthAdminUsersIndexRoute
}

const AuthAdminUsersRouteRouteChildren: AuthAdminUsersRouteRouteChildren = {
  AuthAdminUsersUserIdRoute: AuthAdminUsersUserIdRoute,
  AuthAdminUsersCreateRoute: AuthAdminUsersCreateRoute,
  AuthAdminUsersIndexRoute: AuthAdminUsersIndexRoute,
}

const AuthAdminUsersRouteRouteWithChildren =
  AuthAdminUsersRouteRoute._addFileChildren(AuthAdminUsersRouteRouteChildren)

interface AuthAdminRouteRouteChildren {
  AuthAdminUsersRouteRoute: typeof AuthAdminUsersRouteRouteWithChildren
  AuthAdminImportsIndexRoute: typeof AuthAdminImportsIndexRoute
  AuthAdminImportsAmazonBundlesReportIdRoute: typeof AuthAdminImportsAmazonBundlesReportIdRoute
  AuthAdminImportsAmazonOrdersReportIdRoute: typeof AuthAdminImportsAmazonOrdersReportIdRoute
  AuthAdminImportsCustomersReportIdRoute: typeof AuthAdminImportsCustomersReportIdRoute
  AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute: typeof AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute
  AuthAdminImportsSellInOrdersConfirmedReportIdRoute: typeof AuthAdminImportsSellInOrdersConfirmedReportIdRoute
  AuthAdminImportsSellInOrdersReportIdRoute: typeof AuthAdminImportsSellInOrdersReportIdRoute
  AuthAdminImportsSellInTargetsReportIdRoute: typeof AuthAdminImportsSellInTargetsReportIdRoute
  AuthAdminImportsSellOutRabbaReportIdRoute: typeof AuthAdminImportsSellOutRabbaReportIdRoute
  AuthAdminImportsAmazonBundlesIndexRoute: typeof AuthAdminImportsAmazonBundlesIndexRoute
  AuthAdminImportsAmazonOrdersIndexRoute: typeof AuthAdminImportsAmazonOrdersIndexRoute
  AuthAdminImportsCustomersIndexRoute: typeof AuthAdminImportsCustomersIndexRoute
  AuthAdminImportsProductFormatsIndexRoute: typeof AuthAdminImportsProductFormatsIndexRoute
  AuthAdminImportsProductsIndexRoute: typeof AuthAdminImportsProductsIndexRoute
  AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute: typeof AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute
  AuthAdminImportsSellInOrdersConfirmedIndexRoute: typeof AuthAdminImportsSellInOrdersConfirmedIndexRoute
  AuthAdminImportsSellInOrdersIndexRoute: typeof AuthAdminImportsSellInOrdersIndexRoute
  AuthAdminImportsSellInTargetsIndexRoute: typeof AuthAdminImportsSellInTargetsIndexRoute
  AuthAdminImportsSellOutRabbaIndexRoute: typeof AuthAdminImportsSellOutRabbaIndexRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminUsersRouteRoute: AuthAdminUsersRouteRouteWithChildren,
  AuthAdminImportsIndexRoute: AuthAdminImportsIndexRoute,
  AuthAdminImportsAmazonBundlesReportIdRoute:
    AuthAdminImportsAmazonBundlesReportIdRoute,
  AuthAdminImportsAmazonOrdersReportIdRoute:
    AuthAdminImportsAmazonOrdersReportIdRoute,
  AuthAdminImportsCustomersReportIdRoute:
    AuthAdminImportsCustomersReportIdRoute,
  AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute:
    AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute,
  AuthAdminImportsSellInOrdersConfirmedReportIdRoute:
    AuthAdminImportsSellInOrdersConfirmedReportIdRoute,
  AuthAdminImportsSellInOrdersReportIdRoute:
    AuthAdminImportsSellInOrdersReportIdRoute,
  AuthAdminImportsSellInTargetsReportIdRoute:
    AuthAdminImportsSellInTargetsReportIdRoute,
  AuthAdminImportsSellOutRabbaReportIdRoute:
    AuthAdminImportsSellOutRabbaReportIdRoute,
  AuthAdminImportsAmazonBundlesIndexRoute:
    AuthAdminImportsAmazonBundlesIndexRoute,
  AuthAdminImportsAmazonOrdersIndexRoute:
    AuthAdminImportsAmazonOrdersIndexRoute,
  AuthAdminImportsCustomersIndexRoute: AuthAdminImportsCustomersIndexRoute,
  AuthAdminImportsProductFormatsIndexRoute:
    AuthAdminImportsProductFormatsIndexRoute,
  AuthAdminImportsProductsIndexRoute: AuthAdminImportsProductsIndexRoute,
  AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute:
    AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute,
  AuthAdminImportsSellInOrdersConfirmedIndexRoute:
    AuthAdminImportsSellInOrdersConfirmedIndexRoute,
  AuthAdminImportsSellInOrdersIndexRoute:
    AuthAdminImportsSellInOrdersIndexRoute,
  AuthAdminImportsSellInTargetsIndexRoute:
    AuthAdminImportsSellInTargetsIndexRoute,
  AuthAdminImportsSellOutRabbaIndexRoute:
    AuthAdminImportsSellOutRabbaIndexRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthExampleRouteRouteChildren {
  AuthExampleClientsClientIdRoute: typeof AuthExampleClientsClientIdRoute
  AuthExampleClientsNewRoute: typeof AuthExampleClientsNewRoute
  AuthExampleMyUploadsUploadIdRoute: typeof AuthExampleMyUploadsUploadIdRoute
  AuthExampleOrdersOrderIdRoute: typeof AuthExampleOrdersOrderIdRoute
  AuthExampleOrdersNewRoute: typeof AuthExampleOrdersNewRoute
  AuthExampleClientsIndexRoute: typeof AuthExampleClientsIndexRoute
  AuthExampleKitchenSinkIndexRoute: typeof AuthExampleKitchenSinkIndexRoute
  AuthExampleMyUploadsIndexRoute: typeof AuthExampleMyUploadsIndexRoute
  AuthExampleOrdersIndexRoute: typeof AuthExampleOrdersIndexRoute
  AuthExampleUploadIndexRoute: typeof AuthExampleUploadIndexRoute
}

const AuthExampleRouteRouteChildren: AuthExampleRouteRouteChildren = {
  AuthExampleClientsClientIdRoute: AuthExampleClientsClientIdRoute,
  AuthExampleClientsNewRoute: AuthExampleClientsNewRoute,
  AuthExampleMyUploadsUploadIdRoute: AuthExampleMyUploadsUploadIdRoute,
  AuthExampleOrdersOrderIdRoute: AuthExampleOrdersOrderIdRoute,
  AuthExampleOrdersNewRoute: AuthExampleOrdersNewRoute,
  AuthExampleClientsIndexRoute: AuthExampleClientsIndexRoute,
  AuthExampleKitchenSinkIndexRoute: AuthExampleKitchenSinkIndexRoute,
  AuthExampleMyUploadsIndexRoute: AuthExampleMyUploadsIndexRoute,
  AuthExampleOrdersIndexRoute: AuthExampleOrdersIndexRoute,
  AuthExampleUploadIndexRoute: AuthExampleUploadIndexRoute,
}

const AuthExampleRouteRouteWithChildren =
  AuthExampleRouteRoute._addFileChildren(AuthExampleRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthExampleRouteRoute: typeof AuthExampleRouteRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  AuthNotFoundRoute: typeof AuthNotFoundRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthExampleRouteRoute: AuthExampleRouteRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  AuthNotFoundRoute: AuthNotFoundRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
