/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUnauthorizedRouteImport } from './routes/_auth/unauthorized'
import { Route as AuthSelloutRouteImport } from './routes/_auth/sellout'
import { Route as AuthReportsRouteImport } from './routes/_auth/reports'
import { Route as AuthNotFoundRouteImport } from './routes/_auth/not-found'
import { Route as AuthInventoryRouteImport } from './routes/_auth/inventory'
import { Route as AuthErrorRouteImport } from './routes/_auth/error'
import { Route as AuthCommercialRouteImport } from './routes/_auth/commercial'
import { Route as AuthAmazonRouteImport } from './routes/_auth/amazon'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as AuthAdminUsersRouteRouteImport } from './routes/_auth/admin/users/route'
import { Route as AuthAdminUsersIndexRouteImport } from './routes/_auth/admin/users/index'
import { Route as AuthAdminImportsIndexRouteImport } from './routes/_auth/admin/imports/index'
import { Route as AuthAdminImportsSellOutSobeysIndexRouteImport } from './routes/_auth/admin/imports/sell-out-sobeys/index'
import { Route as AuthAdminImportsSellOutRabbaIndexRouteImport } from './routes/_auth/admin/imports/sell-out-rabba/index'
import { Route as AuthAdminImportsSellOutPetroCanadaIndexRouteImport } from './routes/_auth/admin/imports/sell-out-petro-canada/index'
import { Route as AuthAdminImportsSellOutParklandIndexRouteImport } from './routes/_auth/admin/imports/sell-out-parkland/index'
import { Route as AuthAdminImportsSellOutNapOrangeIndexRouteImport } from './routes/_auth/admin/imports/sell-out-nap-orange/index'
import { Route as AuthAdminImportsSellOutLoblawsIndexRouteImport } from './routes/_auth/admin/imports/sell-out-loblaws/index'
import { Route as AuthAdminImportsSellOutCircleKIndexRouteImport } from './routes/_auth/admin/imports/sell-out-circle-k/index'
import { Route as AuthAdminImportsSellOutCircleKQcatlIndexRouteImport } from './routes/_auth/admin/imports/sell-out-circle-k-qcatl/index'
import { Route as AuthAdminImportsSellOutCentralMarketIndexRouteImport } from './routes/_auth/admin/imports/sell-out-central-market/index'
import { Route as AuthAdminImportsSellOut7ElevenIndexRouteImport } from './routes/_auth/admin/imports/sell-out-7-eleven/index'
import { Route as AuthAdminImportsSellInTargetsIndexRouteImport } from './routes/_auth/admin/imports/sell-in-targets/index'
import { Route as AuthAdminImportsSellInOrdersIndexRouteImport } from './routes/_auth/admin/imports/sell-in-orders/index'
import { Route as AuthAdminImportsSellInOrdersConfirmedIndexRouteImport } from './routes/_auth/admin/imports/sell-in-orders-confirmed/index'
import { Route as AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRouteImport } from './routes/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/index'
import { Route as AuthAdminImportsProductsIndexRouteImport } from './routes/_auth/admin/imports/products/index'
import { Route as AuthAdminImportsProductFormatsIndexRouteImport } from './routes/_auth/admin/imports/product-formats/index'
import { Route as AuthAdminImportsCustomersIndexRouteImport } from './routes/_auth/admin/imports/customers/index'
import { Route as AuthAdminImportsAmazonOrdersIndexRouteImport } from './routes/_auth/admin/imports/amazon-orders/index'
import { Route as AuthAdminImportsAmazonBundlesIndexRouteImport } from './routes/_auth/admin/imports/amazon-bundles/index'
import { Route as AuthAdminImportsSellOutSobeysReportIdRouteImport } from './routes/_auth/admin/imports/sell-out-sobeys/$reportId'
import { Route as AuthAdminImportsSellOutRabbaReportIdRouteImport } from './routes/_auth/admin/imports/sell-out-rabba/$reportId'
import { Route as AuthAdminImportsSellOutPetroCanadaReportIdRouteImport } from './routes/_auth/admin/imports/sell-out-petro-canada/$reportId'
import { Route as AuthAdminImportsSellOutParklandReportIdRouteImport } from './routes/_auth/admin/imports/sell-out-parkland/$reportId'
import { Route as AuthAdminImportsSellOutNapOrangeReportIdRouteImport } from './routes/_auth/admin/imports/sell-out-nap-orange/$reportId'
import { Route as AuthAdminImportsSellOutLoblawsReportIdRouteImport } from './routes/_auth/admin/imports/sell-out-loblaws/$reportId'
import { Route as AuthAdminImportsSellOutCircleKReportIdRouteImport } from './routes/_auth/admin/imports/sell-out-circle-k/$reportId'
import { Route as AuthAdminImportsSellOutCircleKQcatlReportIdRouteImport } from './routes/_auth/admin/imports/sell-out-circle-k-qcatl/$reportId'
import { Route as AuthAdminImportsSellOutCentralMarketReportIdRouteImport } from './routes/_auth/admin/imports/sell-out-central-market/$reportId'
import { Route as AuthAdminImportsSellOut7ElevenReportIdRouteImport } from './routes/_auth/admin/imports/sell-out-7-eleven/$reportId'
import { Route as AuthAdminImportsSellInTargetsReportIdRouteImport } from './routes/_auth/admin/imports/sell-in-targets/$reportId'
import { Route as AuthAdminImportsSellInOrdersReportIdRouteImport } from './routes/_auth/admin/imports/sell-in-orders/$reportId'
import { Route as AuthAdminImportsSellInOrdersConfirmedReportIdRouteImport } from './routes/_auth/admin/imports/sell-in-orders-confirmed/$reportId'
import { Route as AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRouteImport } from './routes/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId'
import { Route as AuthAdminImportsCustomersReportIdRouteImport } from './routes/_auth/admin/imports/customers/$reportId'
import { Route as AuthAdminImportsAmazonOrdersReportIdRouteImport } from './routes/_auth/admin/imports/amazon-orders/$reportId'
import { Route as AuthAdminImportsAmazonBundlesReportIdRouteImport } from './routes/_auth/admin/imports/amazon-bundles/$reportId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSelloutRoute = AuthSelloutRouteImport.update({
  id: '/sellout',
  path: '/sellout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthNotFoundRoute = AuthNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInventoryRoute = AuthInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCommercialRoute = AuthCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAmazonRoute = AuthAmazonRouteImport.update({
  id: '/amazon',
  path: '/amazon',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminUsersRouteRoute = AuthAdminUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminUsersIndexRoute = AuthAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminUsersRouteRoute,
} as any)
const AuthAdminImportsIndexRoute = AuthAdminImportsIndexRouteImport.update({
  id: '/imports/',
  path: '/imports/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminImportsSellOutSobeysIndexRoute =
  AuthAdminImportsSellOutSobeysIndexRouteImport.update({
    id: '/imports/sell-out-sobeys/',
    path: '/imports/sell-out-sobeys/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutRabbaIndexRoute =
  AuthAdminImportsSellOutRabbaIndexRouteImport.update({
    id: '/imports/sell-out-rabba/',
    path: '/imports/sell-out-rabba/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutPetroCanadaIndexRoute =
  AuthAdminImportsSellOutPetroCanadaIndexRouteImport.update({
    id: '/imports/sell-out-petro-canada/',
    path: '/imports/sell-out-petro-canada/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutParklandIndexRoute =
  AuthAdminImportsSellOutParklandIndexRouteImport.update({
    id: '/imports/sell-out-parkland/',
    path: '/imports/sell-out-parkland/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutNapOrangeIndexRoute =
  AuthAdminImportsSellOutNapOrangeIndexRouteImport.update({
    id: '/imports/sell-out-nap-orange/',
    path: '/imports/sell-out-nap-orange/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutLoblawsIndexRoute =
  AuthAdminImportsSellOutLoblawsIndexRouteImport.update({
    id: '/imports/sell-out-loblaws/',
    path: '/imports/sell-out-loblaws/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutCircleKIndexRoute =
  AuthAdminImportsSellOutCircleKIndexRouteImport.update({
    id: '/imports/sell-out-circle-k/',
    path: '/imports/sell-out-circle-k/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutCircleKQcatlIndexRoute =
  AuthAdminImportsSellOutCircleKQcatlIndexRouteImport.update({
    id: '/imports/sell-out-circle-k-qcatl/',
    path: '/imports/sell-out-circle-k-qcatl/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutCentralMarketIndexRoute =
  AuthAdminImportsSellOutCentralMarketIndexRouteImport.update({
    id: '/imports/sell-out-central-market/',
    path: '/imports/sell-out-central-market/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOut7ElevenIndexRoute =
  AuthAdminImportsSellOut7ElevenIndexRouteImport.update({
    id: '/imports/sell-out-7-eleven/',
    path: '/imports/sell-out-7-eleven/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInTargetsIndexRoute =
  AuthAdminImportsSellInTargetsIndexRouteImport.update({
    id: '/imports/sell-in-targets/',
    path: '/imports/sell-in-targets/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInOrdersIndexRoute =
  AuthAdminImportsSellInOrdersIndexRouteImport.update({
    id: '/imports/sell-in-orders/',
    path: '/imports/sell-in-orders/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInOrdersConfirmedIndexRoute =
  AuthAdminImportsSellInOrdersConfirmedIndexRouteImport.update({
    id: '/imports/sell-in-orders-confirmed/',
    path: '/imports/sell-in-orders-confirmed/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute =
  AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRouteImport.update({
    id: '/imports/sell-in-orders-confirmed-7-eleven/',
    path: '/imports/sell-in-orders-confirmed-7-eleven/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsProductsIndexRoute =
  AuthAdminImportsProductsIndexRouteImport.update({
    id: '/imports/products/',
    path: '/imports/products/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsProductFormatsIndexRoute =
  AuthAdminImportsProductFormatsIndexRouteImport.update({
    id: '/imports/product-formats/',
    path: '/imports/product-formats/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsCustomersIndexRoute =
  AuthAdminImportsCustomersIndexRouteImport.update({
    id: '/imports/customers/',
    path: '/imports/customers/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsAmazonOrdersIndexRoute =
  AuthAdminImportsAmazonOrdersIndexRouteImport.update({
    id: '/imports/amazon-orders/',
    path: '/imports/amazon-orders/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsAmazonBundlesIndexRoute =
  AuthAdminImportsAmazonBundlesIndexRouteImport.update({
    id: '/imports/amazon-bundles/',
    path: '/imports/amazon-bundles/',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutSobeysReportIdRoute =
  AuthAdminImportsSellOutSobeysReportIdRouteImport.update({
    id: '/imports/sell-out-sobeys/$reportId',
    path: '/imports/sell-out-sobeys/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutRabbaReportIdRoute =
  AuthAdminImportsSellOutRabbaReportIdRouteImport.update({
    id: '/imports/sell-out-rabba/$reportId',
    path: '/imports/sell-out-rabba/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutPetroCanadaReportIdRoute =
  AuthAdminImportsSellOutPetroCanadaReportIdRouteImport.update({
    id: '/imports/sell-out-petro-canada/$reportId',
    path: '/imports/sell-out-petro-canada/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutParklandReportIdRoute =
  AuthAdminImportsSellOutParklandReportIdRouteImport.update({
    id: '/imports/sell-out-parkland/$reportId',
    path: '/imports/sell-out-parkland/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutNapOrangeReportIdRoute =
  AuthAdminImportsSellOutNapOrangeReportIdRouteImport.update({
    id: '/imports/sell-out-nap-orange/$reportId',
    path: '/imports/sell-out-nap-orange/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutLoblawsReportIdRoute =
  AuthAdminImportsSellOutLoblawsReportIdRouteImport.update({
    id: '/imports/sell-out-loblaws/$reportId',
    path: '/imports/sell-out-loblaws/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutCircleKReportIdRoute =
  AuthAdminImportsSellOutCircleKReportIdRouteImport.update({
    id: '/imports/sell-out-circle-k/$reportId',
    path: '/imports/sell-out-circle-k/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutCircleKQcatlReportIdRoute =
  AuthAdminImportsSellOutCircleKQcatlReportIdRouteImport.update({
    id: '/imports/sell-out-circle-k-qcatl/$reportId',
    path: '/imports/sell-out-circle-k-qcatl/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOutCentralMarketReportIdRoute =
  AuthAdminImportsSellOutCentralMarketReportIdRouteImport.update({
    id: '/imports/sell-out-central-market/$reportId',
    path: '/imports/sell-out-central-market/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellOut7ElevenReportIdRoute =
  AuthAdminImportsSellOut7ElevenReportIdRouteImport.update({
    id: '/imports/sell-out-7-eleven/$reportId',
    path: '/imports/sell-out-7-eleven/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInTargetsReportIdRoute =
  AuthAdminImportsSellInTargetsReportIdRouteImport.update({
    id: '/imports/sell-in-targets/$reportId',
    path: '/imports/sell-in-targets/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInOrdersReportIdRoute =
  AuthAdminImportsSellInOrdersReportIdRouteImport.update({
    id: '/imports/sell-in-orders/$reportId',
    path: '/imports/sell-in-orders/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInOrdersConfirmedReportIdRoute =
  AuthAdminImportsSellInOrdersConfirmedReportIdRouteImport.update({
    id: '/imports/sell-in-orders-confirmed/$reportId',
    path: '/imports/sell-in-orders-confirmed/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute =
  AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRouteImport.update({
    id: '/imports/sell-in-orders-confirmed-7-eleven/$reportId',
    path: '/imports/sell-in-orders-confirmed-7-eleven/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsCustomersReportIdRoute =
  AuthAdminImportsCustomersReportIdRouteImport.update({
    id: '/imports/customers/$reportId',
    path: '/imports/customers/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsAmazonOrdersReportIdRoute =
  AuthAdminImportsAmazonOrdersReportIdRouteImport.update({
    id: '/imports/amazon-orders/$reportId',
    path: '/imports/amazon-orders/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthAdminImportsAmazonBundlesReportIdRoute =
  AuthAdminImportsAmazonBundlesReportIdRouteImport.update({
    id: '/imports/amazon-bundles/$reportId',
    path: '/imports/amazon-bundles/$reportId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/amazon': typeof AuthAmazonRoute
  '/commercial': typeof AuthCommercialRoute
  '/error': typeof AuthErrorRoute
  '/inventory': typeof AuthInventoryRoute
  '/not-found': typeof AuthNotFoundRoute
  '/reports': typeof AuthReportsRoute
  '/sellout': typeof AuthSelloutRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/': typeof AuthIndexRoute
  '/admin/users': typeof AuthAdminUsersRouteRouteWithChildren
  '/admin/imports': typeof AuthAdminImportsIndexRoute
  '/admin/users/': typeof AuthAdminUsersIndexRoute
  '/admin/imports/amazon-bundles/$reportId': typeof AuthAdminImportsAmazonBundlesReportIdRoute
  '/admin/imports/amazon-orders/$reportId': typeof AuthAdminImportsAmazonOrdersReportIdRoute
  '/admin/imports/customers/$reportId': typeof AuthAdminImportsCustomersReportIdRoute
  '/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId': typeof AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute
  '/admin/imports/sell-in-orders-confirmed/$reportId': typeof AuthAdminImportsSellInOrdersConfirmedReportIdRoute
  '/admin/imports/sell-in-orders/$reportId': typeof AuthAdminImportsSellInOrdersReportIdRoute
  '/admin/imports/sell-in-targets/$reportId': typeof AuthAdminImportsSellInTargetsReportIdRoute
  '/admin/imports/sell-out-7-eleven/$reportId': typeof AuthAdminImportsSellOut7ElevenReportIdRoute
  '/admin/imports/sell-out-central-market/$reportId': typeof AuthAdminImportsSellOutCentralMarketReportIdRoute
  '/admin/imports/sell-out-circle-k-qcatl/$reportId': typeof AuthAdminImportsSellOutCircleKQcatlReportIdRoute
  '/admin/imports/sell-out-circle-k/$reportId': typeof AuthAdminImportsSellOutCircleKReportIdRoute
  '/admin/imports/sell-out-loblaws/$reportId': typeof AuthAdminImportsSellOutLoblawsReportIdRoute
  '/admin/imports/sell-out-nap-orange/$reportId': typeof AuthAdminImportsSellOutNapOrangeReportIdRoute
  '/admin/imports/sell-out-parkland/$reportId': typeof AuthAdminImportsSellOutParklandReportIdRoute
  '/admin/imports/sell-out-petro-canada/$reportId': typeof AuthAdminImportsSellOutPetroCanadaReportIdRoute
  '/admin/imports/sell-out-rabba/$reportId': typeof AuthAdminImportsSellOutRabbaReportIdRoute
  '/admin/imports/sell-out-sobeys/$reportId': typeof AuthAdminImportsSellOutSobeysReportIdRoute
  '/admin/imports/amazon-bundles': typeof AuthAdminImportsAmazonBundlesIndexRoute
  '/admin/imports/amazon-orders': typeof AuthAdminImportsAmazonOrdersIndexRoute
  '/admin/imports/customers': typeof AuthAdminImportsCustomersIndexRoute
  '/admin/imports/product-formats': typeof AuthAdminImportsProductFormatsIndexRoute
  '/admin/imports/products': typeof AuthAdminImportsProductsIndexRoute
  '/admin/imports/sell-in-orders-confirmed-7-eleven': typeof AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute
  '/admin/imports/sell-in-orders-confirmed': typeof AuthAdminImportsSellInOrdersConfirmedIndexRoute
  '/admin/imports/sell-in-orders': typeof AuthAdminImportsSellInOrdersIndexRoute
  '/admin/imports/sell-in-targets': typeof AuthAdminImportsSellInTargetsIndexRoute
  '/admin/imports/sell-out-7-eleven': typeof AuthAdminImportsSellOut7ElevenIndexRoute
  '/admin/imports/sell-out-central-market': typeof AuthAdminImportsSellOutCentralMarketIndexRoute
  '/admin/imports/sell-out-circle-k-qcatl': typeof AuthAdminImportsSellOutCircleKQcatlIndexRoute
  '/admin/imports/sell-out-circle-k': typeof AuthAdminImportsSellOutCircleKIndexRoute
  '/admin/imports/sell-out-loblaws': typeof AuthAdminImportsSellOutLoblawsIndexRoute
  '/admin/imports/sell-out-nap-orange': typeof AuthAdminImportsSellOutNapOrangeIndexRoute
  '/admin/imports/sell-out-parkland': typeof AuthAdminImportsSellOutParklandIndexRoute
  '/admin/imports/sell-out-petro-canada': typeof AuthAdminImportsSellOutPetroCanadaIndexRoute
  '/admin/imports/sell-out-rabba': typeof AuthAdminImportsSellOutRabbaIndexRoute
  '/admin/imports/sell-out-sobeys': typeof AuthAdminImportsSellOutSobeysIndexRoute
}
export interface FileRoutesByTo {
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/amazon': typeof AuthAmazonRoute
  '/commercial': typeof AuthCommercialRoute
  '/error': typeof AuthErrorRoute
  '/inventory': typeof AuthInventoryRoute
  '/not-found': typeof AuthNotFoundRoute
  '/reports': typeof AuthReportsRoute
  '/sellout': typeof AuthSelloutRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/': typeof AuthIndexRoute
  '/admin/imports': typeof AuthAdminImportsIndexRoute
  '/admin/users': typeof AuthAdminUsersIndexRoute
  '/admin/imports/amazon-bundles/$reportId': typeof AuthAdminImportsAmazonBundlesReportIdRoute
  '/admin/imports/amazon-orders/$reportId': typeof AuthAdminImportsAmazonOrdersReportIdRoute
  '/admin/imports/customers/$reportId': typeof AuthAdminImportsCustomersReportIdRoute
  '/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId': typeof AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute
  '/admin/imports/sell-in-orders-confirmed/$reportId': typeof AuthAdminImportsSellInOrdersConfirmedReportIdRoute
  '/admin/imports/sell-in-orders/$reportId': typeof AuthAdminImportsSellInOrdersReportIdRoute
  '/admin/imports/sell-in-targets/$reportId': typeof AuthAdminImportsSellInTargetsReportIdRoute
  '/admin/imports/sell-out-7-eleven/$reportId': typeof AuthAdminImportsSellOut7ElevenReportIdRoute
  '/admin/imports/sell-out-central-market/$reportId': typeof AuthAdminImportsSellOutCentralMarketReportIdRoute
  '/admin/imports/sell-out-circle-k-qcatl/$reportId': typeof AuthAdminImportsSellOutCircleKQcatlReportIdRoute
  '/admin/imports/sell-out-circle-k/$reportId': typeof AuthAdminImportsSellOutCircleKReportIdRoute
  '/admin/imports/sell-out-loblaws/$reportId': typeof AuthAdminImportsSellOutLoblawsReportIdRoute
  '/admin/imports/sell-out-nap-orange/$reportId': typeof AuthAdminImportsSellOutNapOrangeReportIdRoute
  '/admin/imports/sell-out-parkland/$reportId': typeof AuthAdminImportsSellOutParklandReportIdRoute
  '/admin/imports/sell-out-petro-canada/$reportId': typeof AuthAdminImportsSellOutPetroCanadaReportIdRoute
  '/admin/imports/sell-out-rabba/$reportId': typeof AuthAdminImportsSellOutRabbaReportIdRoute
  '/admin/imports/sell-out-sobeys/$reportId': typeof AuthAdminImportsSellOutSobeysReportIdRoute
  '/admin/imports/amazon-bundles': typeof AuthAdminImportsAmazonBundlesIndexRoute
  '/admin/imports/amazon-orders': typeof AuthAdminImportsAmazonOrdersIndexRoute
  '/admin/imports/customers': typeof AuthAdminImportsCustomersIndexRoute
  '/admin/imports/product-formats': typeof AuthAdminImportsProductFormatsIndexRoute
  '/admin/imports/products': typeof AuthAdminImportsProductsIndexRoute
  '/admin/imports/sell-in-orders-confirmed-7-eleven': typeof AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute
  '/admin/imports/sell-in-orders-confirmed': typeof AuthAdminImportsSellInOrdersConfirmedIndexRoute
  '/admin/imports/sell-in-orders': typeof AuthAdminImportsSellInOrdersIndexRoute
  '/admin/imports/sell-in-targets': typeof AuthAdminImportsSellInTargetsIndexRoute
  '/admin/imports/sell-out-7-eleven': typeof AuthAdminImportsSellOut7ElevenIndexRoute
  '/admin/imports/sell-out-central-market': typeof AuthAdminImportsSellOutCentralMarketIndexRoute
  '/admin/imports/sell-out-circle-k-qcatl': typeof AuthAdminImportsSellOutCircleKQcatlIndexRoute
  '/admin/imports/sell-out-circle-k': typeof AuthAdminImportsSellOutCircleKIndexRoute
  '/admin/imports/sell-out-loblaws': typeof AuthAdminImportsSellOutLoblawsIndexRoute
  '/admin/imports/sell-out-nap-orange': typeof AuthAdminImportsSellOutNapOrangeIndexRoute
  '/admin/imports/sell-out-parkland': typeof AuthAdminImportsSellOutParklandIndexRoute
  '/admin/imports/sell-out-petro-canada': typeof AuthAdminImportsSellOutPetroCanadaIndexRoute
  '/admin/imports/sell-out-rabba': typeof AuthAdminImportsSellOutRabbaIndexRoute
  '/admin/imports/sell-out-sobeys': typeof AuthAdminImportsSellOutSobeysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/amazon': typeof AuthAmazonRoute
  '/_auth/commercial': typeof AuthCommercialRoute
  '/_auth/error': typeof AuthErrorRoute
  '/_auth/inventory': typeof AuthInventoryRoute
  '/_auth/not-found': typeof AuthNotFoundRoute
  '/_auth/reports': typeof AuthReportsRoute
  '/_auth/sellout': typeof AuthSelloutRoute
  '/_auth/unauthorized': typeof AuthUnauthorizedRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin/users': typeof AuthAdminUsersRouteRouteWithChildren
  '/_auth/admin/imports/': typeof AuthAdminImportsIndexRoute
  '/_auth/admin/users/': typeof AuthAdminUsersIndexRoute
  '/_auth/admin/imports/amazon-bundles/$reportId': typeof AuthAdminImportsAmazonBundlesReportIdRoute
  '/_auth/admin/imports/amazon-orders/$reportId': typeof AuthAdminImportsAmazonOrdersReportIdRoute
  '/_auth/admin/imports/customers/$reportId': typeof AuthAdminImportsCustomersReportIdRoute
  '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId': typeof AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute
  '/_auth/admin/imports/sell-in-orders-confirmed/$reportId': typeof AuthAdminImportsSellInOrdersConfirmedReportIdRoute
  '/_auth/admin/imports/sell-in-orders/$reportId': typeof AuthAdminImportsSellInOrdersReportIdRoute
  '/_auth/admin/imports/sell-in-targets/$reportId': typeof AuthAdminImportsSellInTargetsReportIdRoute
  '/_auth/admin/imports/sell-out-7-eleven/$reportId': typeof AuthAdminImportsSellOut7ElevenReportIdRoute
  '/_auth/admin/imports/sell-out-central-market/$reportId': typeof AuthAdminImportsSellOutCentralMarketReportIdRoute
  '/_auth/admin/imports/sell-out-circle-k-qcatl/$reportId': typeof AuthAdminImportsSellOutCircleKQcatlReportIdRoute
  '/_auth/admin/imports/sell-out-circle-k/$reportId': typeof AuthAdminImportsSellOutCircleKReportIdRoute
  '/_auth/admin/imports/sell-out-loblaws/$reportId': typeof AuthAdminImportsSellOutLoblawsReportIdRoute
  '/_auth/admin/imports/sell-out-nap-orange/$reportId': typeof AuthAdminImportsSellOutNapOrangeReportIdRoute
  '/_auth/admin/imports/sell-out-parkland/$reportId': typeof AuthAdminImportsSellOutParklandReportIdRoute
  '/_auth/admin/imports/sell-out-petro-canada/$reportId': typeof AuthAdminImportsSellOutPetroCanadaReportIdRoute
  '/_auth/admin/imports/sell-out-rabba/$reportId': typeof AuthAdminImportsSellOutRabbaReportIdRoute
  '/_auth/admin/imports/sell-out-sobeys/$reportId': typeof AuthAdminImportsSellOutSobeysReportIdRoute
  '/_auth/admin/imports/amazon-bundles/': typeof AuthAdminImportsAmazonBundlesIndexRoute
  '/_auth/admin/imports/amazon-orders/': typeof AuthAdminImportsAmazonOrdersIndexRoute
  '/_auth/admin/imports/customers/': typeof AuthAdminImportsCustomersIndexRoute
  '/_auth/admin/imports/product-formats/': typeof AuthAdminImportsProductFormatsIndexRoute
  '/_auth/admin/imports/products/': typeof AuthAdminImportsProductsIndexRoute
  '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/': typeof AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute
  '/_auth/admin/imports/sell-in-orders-confirmed/': typeof AuthAdminImportsSellInOrdersConfirmedIndexRoute
  '/_auth/admin/imports/sell-in-orders/': typeof AuthAdminImportsSellInOrdersIndexRoute
  '/_auth/admin/imports/sell-in-targets/': typeof AuthAdminImportsSellInTargetsIndexRoute
  '/_auth/admin/imports/sell-out-7-eleven/': typeof AuthAdminImportsSellOut7ElevenIndexRoute
  '/_auth/admin/imports/sell-out-central-market/': typeof AuthAdminImportsSellOutCentralMarketIndexRoute
  '/_auth/admin/imports/sell-out-circle-k-qcatl/': typeof AuthAdminImportsSellOutCircleKQcatlIndexRoute
  '/_auth/admin/imports/sell-out-circle-k/': typeof AuthAdminImportsSellOutCircleKIndexRoute
  '/_auth/admin/imports/sell-out-loblaws/': typeof AuthAdminImportsSellOutLoblawsIndexRoute
  '/_auth/admin/imports/sell-out-nap-orange/': typeof AuthAdminImportsSellOutNapOrangeIndexRoute
  '/_auth/admin/imports/sell-out-parkland/': typeof AuthAdminImportsSellOutParklandIndexRoute
  '/_auth/admin/imports/sell-out-petro-canada/': typeof AuthAdminImportsSellOutPetroCanadaIndexRoute
  '/_auth/admin/imports/sell-out-rabba/': typeof AuthAdminImportsSellOutRabbaIndexRoute
  '/_auth/admin/imports/sell-out-sobeys/': typeof AuthAdminImportsSellOutSobeysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/join'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/amazon'
    | '/commercial'
    | '/error'
    | '/inventory'
    | '/not-found'
    | '/reports'
    | '/sellout'
    | '/unauthorized'
    | '/'
    | '/admin/users'
    | '/admin/imports'
    | '/admin/users/'
    | '/admin/imports/amazon-bundles/$reportId'
    | '/admin/imports/amazon-orders/$reportId'
    | '/admin/imports/customers/$reportId'
    | '/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId'
    | '/admin/imports/sell-in-orders-confirmed/$reportId'
    | '/admin/imports/sell-in-orders/$reportId'
    | '/admin/imports/sell-in-targets/$reportId'
    | '/admin/imports/sell-out-7-eleven/$reportId'
    | '/admin/imports/sell-out-central-market/$reportId'
    | '/admin/imports/sell-out-circle-k-qcatl/$reportId'
    | '/admin/imports/sell-out-circle-k/$reportId'
    | '/admin/imports/sell-out-loblaws/$reportId'
    | '/admin/imports/sell-out-nap-orange/$reportId'
    | '/admin/imports/sell-out-parkland/$reportId'
    | '/admin/imports/sell-out-petro-canada/$reportId'
    | '/admin/imports/sell-out-rabba/$reportId'
    | '/admin/imports/sell-out-sobeys/$reportId'
    | '/admin/imports/amazon-bundles'
    | '/admin/imports/amazon-orders'
    | '/admin/imports/customers'
    | '/admin/imports/product-formats'
    | '/admin/imports/products'
    | '/admin/imports/sell-in-orders-confirmed-7-eleven'
    | '/admin/imports/sell-in-orders-confirmed'
    | '/admin/imports/sell-in-orders'
    | '/admin/imports/sell-in-targets'
    | '/admin/imports/sell-out-7-eleven'
    | '/admin/imports/sell-out-central-market'
    | '/admin/imports/sell-out-circle-k-qcatl'
    | '/admin/imports/sell-out-circle-k'
    | '/admin/imports/sell-out-loblaws'
    | '/admin/imports/sell-out-nap-orange'
    | '/admin/imports/sell-out-parkland'
    | '/admin/imports/sell-out-petro-canada'
    | '/admin/imports/sell-out-rabba'
    | '/admin/imports/sell-out-sobeys'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/join'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/amazon'
    | '/commercial'
    | '/error'
    | '/inventory'
    | '/not-found'
    | '/reports'
    | '/sellout'
    | '/unauthorized'
    | '/'
    | '/admin/imports'
    | '/admin/users'
    | '/admin/imports/amazon-bundles/$reportId'
    | '/admin/imports/amazon-orders/$reportId'
    | '/admin/imports/customers/$reportId'
    | '/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId'
    | '/admin/imports/sell-in-orders-confirmed/$reportId'
    | '/admin/imports/sell-in-orders/$reportId'
    | '/admin/imports/sell-in-targets/$reportId'
    | '/admin/imports/sell-out-7-eleven/$reportId'
    | '/admin/imports/sell-out-central-market/$reportId'
    | '/admin/imports/sell-out-circle-k-qcatl/$reportId'
    | '/admin/imports/sell-out-circle-k/$reportId'
    | '/admin/imports/sell-out-loblaws/$reportId'
    | '/admin/imports/sell-out-nap-orange/$reportId'
    | '/admin/imports/sell-out-parkland/$reportId'
    | '/admin/imports/sell-out-petro-canada/$reportId'
    | '/admin/imports/sell-out-rabba/$reportId'
    | '/admin/imports/sell-out-sobeys/$reportId'
    | '/admin/imports/amazon-bundles'
    | '/admin/imports/amazon-orders'
    | '/admin/imports/customers'
    | '/admin/imports/product-formats'
    | '/admin/imports/products'
    | '/admin/imports/sell-in-orders-confirmed-7-eleven'
    | '/admin/imports/sell-in-orders-confirmed'
    | '/admin/imports/sell-in-orders'
    | '/admin/imports/sell-in-targets'
    | '/admin/imports/sell-out-7-eleven'
    | '/admin/imports/sell-out-central-market'
    | '/admin/imports/sell-out-circle-k-qcatl'
    | '/admin/imports/sell-out-circle-k'
    | '/admin/imports/sell-out-loblaws'
    | '/admin/imports/sell-out-nap-orange'
    | '/admin/imports/sell-out-parkland'
    | '/admin/imports/sell-out-petro-canada'
    | '/admin/imports/sell-out-rabba'
    | '/admin/imports/sell-out-sobeys'
  id:
    | '__root__'
    | '/_auth'
    | '/join'
    | '/login'
    | '/reset-password'
    | '/_auth/admin'
    | '/_auth/amazon'
    | '/_auth/commercial'
    | '/_auth/error'
    | '/_auth/inventory'
    | '/_auth/not-found'
    | '/_auth/reports'
    | '/_auth/sellout'
    | '/_auth/unauthorized'
    | '/_auth/'
    | '/_auth/admin/users'
    | '/_auth/admin/imports/'
    | '/_auth/admin/users/'
    | '/_auth/admin/imports/amazon-bundles/$reportId'
    | '/_auth/admin/imports/amazon-orders/$reportId'
    | '/_auth/admin/imports/customers/$reportId'
    | '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId'
    | '/_auth/admin/imports/sell-in-orders-confirmed/$reportId'
    | '/_auth/admin/imports/sell-in-orders/$reportId'
    | '/_auth/admin/imports/sell-in-targets/$reportId'
    | '/_auth/admin/imports/sell-out-7-eleven/$reportId'
    | '/_auth/admin/imports/sell-out-central-market/$reportId'
    | '/_auth/admin/imports/sell-out-circle-k-qcatl/$reportId'
    | '/_auth/admin/imports/sell-out-circle-k/$reportId'
    | '/_auth/admin/imports/sell-out-loblaws/$reportId'
    | '/_auth/admin/imports/sell-out-nap-orange/$reportId'
    | '/_auth/admin/imports/sell-out-parkland/$reportId'
    | '/_auth/admin/imports/sell-out-petro-canada/$reportId'
    | '/_auth/admin/imports/sell-out-rabba/$reportId'
    | '/_auth/admin/imports/sell-out-sobeys/$reportId'
    | '/_auth/admin/imports/amazon-bundles/'
    | '/_auth/admin/imports/amazon-orders/'
    | '/_auth/admin/imports/customers/'
    | '/_auth/admin/imports/product-formats/'
    | '/_auth/admin/imports/products/'
    | '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/'
    | '/_auth/admin/imports/sell-in-orders-confirmed/'
    | '/_auth/admin/imports/sell-in-orders/'
    | '/_auth/admin/imports/sell-in-targets/'
    | '/_auth/admin/imports/sell-out-7-eleven/'
    | '/_auth/admin/imports/sell-out-central-market/'
    | '/_auth/admin/imports/sell-out-circle-k-qcatl/'
    | '/_auth/admin/imports/sell-out-circle-k/'
    | '/_auth/admin/imports/sell-out-loblaws/'
    | '/_auth/admin/imports/sell-out-nap-orange/'
    | '/_auth/admin/imports/sell-out-parkland/'
    | '/_auth/admin/imports/sell-out-petro-canada/'
    | '/_auth/admin/imports/sell-out-rabba/'
    | '/_auth/admin/imports/sell-out-sobeys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/unauthorized': {
      id: '/_auth/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sellout': {
      id: '/_auth/sellout'
      path: '/sellout'
      fullPath: '/sellout'
      preLoaderRoute: typeof AuthSelloutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/not-found': {
      id: '/_auth/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof AuthNotFoundRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/inventory': {
      id: '/_auth/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthInventoryRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/error': {
      id: '/_auth/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/commercial': {
      id: '/_auth/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof AuthCommercialRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/amazon': {
      id: '/_auth/amazon'
      path: '/amazon'
      fullPath: '/amazon'
      preLoaderRoute: typeof AuthAmazonRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/users/': {
      id: '/_auth/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthAdminUsersIndexRouteImport
      parentRoute: typeof AuthAdminUsersRouteRoute
    }
    '/_auth/admin/imports/': {
      id: '/_auth/admin/imports/'
      path: '/imports'
      fullPath: '/admin/imports'
      preLoaderRoute: typeof AuthAdminImportsIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-sobeys/': {
      id: '/_auth/admin/imports/sell-out-sobeys/'
      path: '/imports/sell-out-sobeys'
      fullPath: '/admin/imports/sell-out-sobeys'
      preLoaderRoute: typeof AuthAdminImportsSellOutSobeysIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-rabba/': {
      id: '/_auth/admin/imports/sell-out-rabba/'
      path: '/imports/sell-out-rabba'
      fullPath: '/admin/imports/sell-out-rabba'
      preLoaderRoute: typeof AuthAdminImportsSellOutRabbaIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-petro-canada/': {
      id: '/_auth/admin/imports/sell-out-petro-canada/'
      path: '/imports/sell-out-petro-canada'
      fullPath: '/admin/imports/sell-out-petro-canada'
      preLoaderRoute: typeof AuthAdminImportsSellOutPetroCanadaIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-parkland/': {
      id: '/_auth/admin/imports/sell-out-parkland/'
      path: '/imports/sell-out-parkland'
      fullPath: '/admin/imports/sell-out-parkland'
      preLoaderRoute: typeof AuthAdminImportsSellOutParklandIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-nap-orange/': {
      id: '/_auth/admin/imports/sell-out-nap-orange/'
      path: '/imports/sell-out-nap-orange'
      fullPath: '/admin/imports/sell-out-nap-orange'
      preLoaderRoute: typeof AuthAdminImportsSellOutNapOrangeIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-loblaws/': {
      id: '/_auth/admin/imports/sell-out-loblaws/'
      path: '/imports/sell-out-loblaws'
      fullPath: '/admin/imports/sell-out-loblaws'
      preLoaderRoute: typeof AuthAdminImportsSellOutLoblawsIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-circle-k/': {
      id: '/_auth/admin/imports/sell-out-circle-k/'
      path: '/imports/sell-out-circle-k'
      fullPath: '/admin/imports/sell-out-circle-k'
      preLoaderRoute: typeof AuthAdminImportsSellOutCircleKIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-circle-k-qcatl/': {
      id: '/_auth/admin/imports/sell-out-circle-k-qcatl/'
      path: '/imports/sell-out-circle-k-qcatl'
      fullPath: '/admin/imports/sell-out-circle-k-qcatl'
      preLoaderRoute: typeof AuthAdminImportsSellOutCircleKQcatlIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-central-market/': {
      id: '/_auth/admin/imports/sell-out-central-market/'
      path: '/imports/sell-out-central-market'
      fullPath: '/admin/imports/sell-out-central-market'
      preLoaderRoute: typeof AuthAdminImportsSellOutCentralMarketIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-7-eleven/': {
      id: '/_auth/admin/imports/sell-out-7-eleven/'
      path: '/imports/sell-out-7-eleven'
      fullPath: '/admin/imports/sell-out-7-eleven'
      preLoaderRoute: typeof AuthAdminImportsSellOut7ElevenIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-targets/': {
      id: '/_auth/admin/imports/sell-in-targets/'
      path: '/imports/sell-in-targets'
      fullPath: '/admin/imports/sell-in-targets'
      preLoaderRoute: typeof AuthAdminImportsSellInTargetsIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-orders/': {
      id: '/_auth/admin/imports/sell-in-orders/'
      path: '/imports/sell-in-orders'
      fullPath: '/admin/imports/sell-in-orders'
      preLoaderRoute: typeof AuthAdminImportsSellInOrdersIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-orders-confirmed/': {
      id: '/_auth/admin/imports/sell-in-orders-confirmed/'
      path: '/imports/sell-in-orders-confirmed'
      fullPath: '/admin/imports/sell-in-orders-confirmed'
      preLoaderRoute: typeof AuthAdminImportsSellInOrdersConfirmedIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/': {
      id: '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/'
      path: '/imports/sell-in-orders-confirmed-7-eleven'
      fullPath: '/admin/imports/sell-in-orders-confirmed-7-eleven'
      preLoaderRoute: typeof AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/products/': {
      id: '/_auth/admin/imports/products/'
      path: '/imports/products'
      fullPath: '/admin/imports/products'
      preLoaderRoute: typeof AuthAdminImportsProductsIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/product-formats/': {
      id: '/_auth/admin/imports/product-formats/'
      path: '/imports/product-formats'
      fullPath: '/admin/imports/product-formats'
      preLoaderRoute: typeof AuthAdminImportsProductFormatsIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/customers/': {
      id: '/_auth/admin/imports/customers/'
      path: '/imports/customers'
      fullPath: '/admin/imports/customers'
      preLoaderRoute: typeof AuthAdminImportsCustomersIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/amazon-orders/': {
      id: '/_auth/admin/imports/amazon-orders/'
      path: '/imports/amazon-orders'
      fullPath: '/admin/imports/amazon-orders'
      preLoaderRoute: typeof AuthAdminImportsAmazonOrdersIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/amazon-bundles/': {
      id: '/_auth/admin/imports/amazon-bundles/'
      path: '/imports/amazon-bundles'
      fullPath: '/admin/imports/amazon-bundles'
      preLoaderRoute: typeof AuthAdminImportsAmazonBundlesIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-sobeys/$reportId': {
      id: '/_auth/admin/imports/sell-out-sobeys/$reportId'
      path: '/imports/sell-out-sobeys/$reportId'
      fullPath: '/admin/imports/sell-out-sobeys/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellOutSobeysReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-rabba/$reportId': {
      id: '/_auth/admin/imports/sell-out-rabba/$reportId'
      path: '/imports/sell-out-rabba/$reportId'
      fullPath: '/admin/imports/sell-out-rabba/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellOutRabbaReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-petro-canada/$reportId': {
      id: '/_auth/admin/imports/sell-out-petro-canada/$reportId'
      path: '/imports/sell-out-petro-canada/$reportId'
      fullPath: '/admin/imports/sell-out-petro-canada/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellOutPetroCanadaReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-parkland/$reportId': {
      id: '/_auth/admin/imports/sell-out-parkland/$reportId'
      path: '/imports/sell-out-parkland/$reportId'
      fullPath: '/admin/imports/sell-out-parkland/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellOutParklandReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-nap-orange/$reportId': {
      id: '/_auth/admin/imports/sell-out-nap-orange/$reportId'
      path: '/imports/sell-out-nap-orange/$reportId'
      fullPath: '/admin/imports/sell-out-nap-orange/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellOutNapOrangeReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-loblaws/$reportId': {
      id: '/_auth/admin/imports/sell-out-loblaws/$reportId'
      path: '/imports/sell-out-loblaws/$reportId'
      fullPath: '/admin/imports/sell-out-loblaws/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellOutLoblawsReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-circle-k/$reportId': {
      id: '/_auth/admin/imports/sell-out-circle-k/$reportId'
      path: '/imports/sell-out-circle-k/$reportId'
      fullPath: '/admin/imports/sell-out-circle-k/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellOutCircleKReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-circle-k-qcatl/$reportId': {
      id: '/_auth/admin/imports/sell-out-circle-k-qcatl/$reportId'
      path: '/imports/sell-out-circle-k-qcatl/$reportId'
      fullPath: '/admin/imports/sell-out-circle-k-qcatl/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellOutCircleKQcatlReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-central-market/$reportId': {
      id: '/_auth/admin/imports/sell-out-central-market/$reportId'
      path: '/imports/sell-out-central-market/$reportId'
      fullPath: '/admin/imports/sell-out-central-market/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellOutCentralMarketReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-out-7-eleven/$reportId': {
      id: '/_auth/admin/imports/sell-out-7-eleven/$reportId'
      path: '/imports/sell-out-7-eleven/$reportId'
      fullPath: '/admin/imports/sell-out-7-eleven/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellOut7ElevenReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-targets/$reportId': {
      id: '/_auth/admin/imports/sell-in-targets/$reportId'
      path: '/imports/sell-in-targets/$reportId'
      fullPath: '/admin/imports/sell-in-targets/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellInTargetsReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-orders/$reportId': {
      id: '/_auth/admin/imports/sell-in-orders/$reportId'
      path: '/imports/sell-in-orders/$reportId'
      fullPath: '/admin/imports/sell-in-orders/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellInOrdersReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-orders-confirmed/$reportId': {
      id: '/_auth/admin/imports/sell-in-orders-confirmed/$reportId'
      path: '/imports/sell-in-orders-confirmed/$reportId'
      fullPath: '/admin/imports/sell-in-orders-confirmed/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellInOrdersConfirmedReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId': {
      id: '/_auth/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId'
      path: '/imports/sell-in-orders-confirmed-7-eleven/$reportId'
      fullPath: '/admin/imports/sell-in-orders-confirmed-7-eleven/$reportId'
      preLoaderRoute: typeof AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/customers/$reportId': {
      id: '/_auth/admin/imports/customers/$reportId'
      path: '/imports/customers/$reportId'
      fullPath: '/admin/imports/customers/$reportId'
      preLoaderRoute: typeof AuthAdminImportsCustomersReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/amazon-orders/$reportId': {
      id: '/_auth/admin/imports/amazon-orders/$reportId'
      path: '/imports/amazon-orders/$reportId'
      fullPath: '/admin/imports/amazon-orders/$reportId'
      preLoaderRoute: typeof AuthAdminImportsAmazonOrdersReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/imports/amazon-bundles/$reportId': {
      id: '/_auth/admin/imports/amazon-bundles/$reportId'
      path: '/imports/amazon-bundles/$reportId'
      fullPath: '/admin/imports/amazon-bundles/$reportId'
      preLoaderRoute: typeof AuthAdminImportsAmazonBundlesReportIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
  }
}

interface AuthAdminUsersRouteRouteChildren {
  AuthAdminUsersIndexRoute: typeof AuthAdminUsersIndexRoute
}

const AuthAdminUsersRouteRouteChildren: AuthAdminUsersRouteRouteChildren = {
  AuthAdminUsersIndexRoute: AuthAdminUsersIndexRoute,
}

const AuthAdminUsersRouteRouteWithChildren =
  AuthAdminUsersRouteRoute._addFileChildren(AuthAdminUsersRouteRouteChildren)

interface AuthAdminRouteRouteChildren {
  AuthAdminUsersRouteRoute: typeof AuthAdminUsersRouteRouteWithChildren
  AuthAdminImportsIndexRoute: typeof AuthAdminImportsIndexRoute
  AuthAdminImportsAmazonBundlesReportIdRoute: typeof AuthAdminImportsAmazonBundlesReportIdRoute
  AuthAdminImportsAmazonOrdersReportIdRoute: typeof AuthAdminImportsAmazonOrdersReportIdRoute
  AuthAdminImportsCustomersReportIdRoute: typeof AuthAdminImportsCustomersReportIdRoute
  AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute: typeof AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute
  AuthAdminImportsSellInOrdersConfirmedReportIdRoute: typeof AuthAdminImportsSellInOrdersConfirmedReportIdRoute
  AuthAdminImportsSellInOrdersReportIdRoute: typeof AuthAdminImportsSellInOrdersReportIdRoute
  AuthAdminImportsSellInTargetsReportIdRoute: typeof AuthAdminImportsSellInTargetsReportIdRoute
  AuthAdminImportsSellOut7ElevenReportIdRoute: typeof AuthAdminImportsSellOut7ElevenReportIdRoute
  AuthAdminImportsSellOutCentralMarketReportIdRoute: typeof AuthAdminImportsSellOutCentralMarketReportIdRoute
  AuthAdminImportsSellOutCircleKQcatlReportIdRoute: typeof AuthAdminImportsSellOutCircleKQcatlReportIdRoute
  AuthAdminImportsSellOutCircleKReportIdRoute: typeof AuthAdminImportsSellOutCircleKReportIdRoute
  AuthAdminImportsSellOutLoblawsReportIdRoute: typeof AuthAdminImportsSellOutLoblawsReportIdRoute
  AuthAdminImportsSellOutNapOrangeReportIdRoute: typeof AuthAdminImportsSellOutNapOrangeReportIdRoute
  AuthAdminImportsSellOutParklandReportIdRoute: typeof AuthAdminImportsSellOutParklandReportIdRoute
  AuthAdminImportsSellOutPetroCanadaReportIdRoute: typeof AuthAdminImportsSellOutPetroCanadaReportIdRoute
  AuthAdminImportsSellOutRabbaReportIdRoute: typeof AuthAdminImportsSellOutRabbaReportIdRoute
  AuthAdminImportsSellOutSobeysReportIdRoute: typeof AuthAdminImportsSellOutSobeysReportIdRoute
  AuthAdminImportsAmazonBundlesIndexRoute: typeof AuthAdminImportsAmazonBundlesIndexRoute
  AuthAdminImportsAmazonOrdersIndexRoute: typeof AuthAdminImportsAmazonOrdersIndexRoute
  AuthAdminImportsCustomersIndexRoute: typeof AuthAdminImportsCustomersIndexRoute
  AuthAdminImportsProductFormatsIndexRoute: typeof AuthAdminImportsProductFormatsIndexRoute
  AuthAdminImportsProductsIndexRoute: typeof AuthAdminImportsProductsIndexRoute
  AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute: typeof AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute
  AuthAdminImportsSellInOrdersConfirmedIndexRoute: typeof AuthAdminImportsSellInOrdersConfirmedIndexRoute
  AuthAdminImportsSellInOrdersIndexRoute: typeof AuthAdminImportsSellInOrdersIndexRoute
  AuthAdminImportsSellInTargetsIndexRoute: typeof AuthAdminImportsSellInTargetsIndexRoute
  AuthAdminImportsSellOut7ElevenIndexRoute: typeof AuthAdminImportsSellOut7ElevenIndexRoute
  AuthAdminImportsSellOutCentralMarketIndexRoute: typeof AuthAdminImportsSellOutCentralMarketIndexRoute
  AuthAdminImportsSellOutCircleKQcatlIndexRoute: typeof AuthAdminImportsSellOutCircleKQcatlIndexRoute
  AuthAdminImportsSellOutCircleKIndexRoute: typeof AuthAdminImportsSellOutCircleKIndexRoute
  AuthAdminImportsSellOutLoblawsIndexRoute: typeof AuthAdminImportsSellOutLoblawsIndexRoute
  AuthAdminImportsSellOutNapOrangeIndexRoute: typeof AuthAdminImportsSellOutNapOrangeIndexRoute
  AuthAdminImportsSellOutParklandIndexRoute: typeof AuthAdminImportsSellOutParklandIndexRoute
  AuthAdminImportsSellOutPetroCanadaIndexRoute: typeof AuthAdminImportsSellOutPetroCanadaIndexRoute
  AuthAdminImportsSellOutRabbaIndexRoute: typeof AuthAdminImportsSellOutRabbaIndexRoute
  AuthAdminImportsSellOutSobeysIndexRoute: typeof AuthAdminImportsSellOutSobeysIndexRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminUsersRouteRoute: AuthAdminUsersRouteRouteWithChildren,
  AuthAdminImportsIndexRoute: AuthAdminImportsIndexRoute,
  AuthAdminImportsAmazonBundlesReportIdRoute:
    AuthAdminImportsAmazonBundlesReportIdRoute,
  AuthAdminImportsAmazonOrdersReportIdRoute:
    AuthAdminImportsAmazonOrdersReportIdRoute,
  AuthAdminImportsCustomersReportIdRoute:
    AuthAdminImportsCustomersReportIdRoute,
  AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute:
    AuthAdminImportsSellInOrdersConfirmed7ElevenReportIdRoute,
  AuthAdminImportsSellInOrdersConfirmedReportIdRoute:
    AuthAdminImportsSellInOrdersConfirmedReportIdRoute,
  AuthAdminImportsSellInOrdersReportIdRoute:
    AuthAdminImportsSellInOrdersReportIdRoute,
  AuthAdminImportsSellInTargetsReportIdRoute:
    AuthAdminImportsSellInTargetsReportIdRoute,
  AuthAdminImportsSellOut7ElevenReportIdRoute:
    AuthAdminImportsSellOut7ElevenReportIdRoute,
  AuthAdminImportsSellOutCentralMarketReportIdRoute:
    AuthAdminImportsSellOutCentralMarketReportIdRoute,
  AuthAdminImportsSellOutCircleKQcatlReportIdRoute:
    AuthAdminImportsSellOutCircleKQcatlReportIdRoute,
  AuthAdminImportsSellOutCircleKReportIdRoute:
    AuthAdminImportsSellOutCircleKReportIdRoute,
  AuthAdminImportsSellOutLoblawsReportIdRoute:
    AuthAdminImportsSellOutLoblawsReportIdRoute,
  AuthAdminImportsSellOutNapOrangeReportIdRoute:
    AuthAdminImportsSellOutNapOrangeReportIdRoute,
  AuthAdminImportsSellOutParklandReportIdRoute:
    AuthAdminImportsSellOutParklandReportIdRoute,
  AuthAdminImportsSellOutPetroCanadaReportIdRoute:
    AuthAdminImportsSellOutPetroCanadaReportIdRoute,
  AuthAdminImportsSellOutRabbaReportIdRoute:
    AuthAdminImportsSellOutRabbaReportIdRoute,
  AuthAdminImportsSellOutSobeysReportIdRoute:
    AuthAdminImportsSellOutSobeysReportIdRoute,
  AuthAdminImportsAmazonBundlesIndexRoute:
    AuthAdminImportsAmazonBundlesIndexRoute,
  AuthAdminImportsAmazonOrdersIndexRoute:
    AuthAdminImportsAmazonOrdersIndexRoute,
  AuthAdminImportsCustomersIndexRoute: AuthAdminImportsCustomersIndexRoute,
  AuthAdminImportsProductFormatsIndexRoute:
    AuthAdminImportsProductFormatsIndexRoute,
  AuthAdminImportsProductsIndexRoute: AuthAdminImportsProductsIndexRoute,
  AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute:
    AuthAdminImportsSellInOrdersConfirmed7ElevenIndexRoute,
  AuthAdminImportsSellInOrdersConfirmedIndexRoute:
    AuthAdminImportsSellInOrdersConfirmedIndexRoute,
  AuthAdminImportsSellInOrdersIndexRoute:
    AuthAdminImportsSellInOrdersIndexRoute,
  AuthAdminImportsSellInTargetsIndexRoute:
    AuthAdminImportsSellInTargetsIndexRoute,
  AuthAdminImportsSellOut7ElevenIndexRoute:
    AuthAdminImportsSellOut7ElevenIndexRoute,
  AuthAdminImportsSellOutCentralMarketIndexRoute:
    AuthAdminImportsSellOutCentralMarketIndexRoute,
  AuthAdminImportsSellOutCircleKQcatlIndexRoute:
    AuthAdminImportsSellOutCircleKQcatlIndexRoute,
  AuthAdminImportsSellOutCircleKIndexRoute:
    AuthAdminImportsSellOutCircleKIndexRoute,
  AuthAdminImportsSellOutLoblawsIndexRoute:
    AuthAdminImportsSellOutLoblawsIndexRoute,
  AuthAdminImportsSellOutNapOrangeIndexRoute:
    AuthAdminImportsSellOutNapOrangeIndexRoute,
  AuthAdminImportsSellOutParklandIndexRoute:
    AuthAdminImportsSellOutParklandIndexRoute,
  AuthAdminImportsSellOutPetroCanadaIndexRoute:
    AuthAdminImportsSellOutPetroCanadaIndexRoute,
  AuthAdminImportsSellOutRabbaIndexRoute:
    AuthAdminImportsSellOutRabbaIndexRoute,
  AuthAdminImportsSellOutSobeysIndexRoute:
    AuthAdminImportsSellOutSobeysIndexRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthAmazonRoute: typeof AuthAmazonRoute
  AuthCommercialRoute: typeof AuthCommercialRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthInventoryRoute: typeof AuthInventoryRoute
  AuthNotFoundRoute: typeof AuthNotFoundRoute
  AuthReportsRoute: typeof AuthReportsRoute
  AuthSelloutRoute: typeof AuthSelloutRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthAmazonRoute: AuthAmazonRoute,
  AuthCommercialRoute: AuthCommercialRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthInventoryRoute: AuthInventoryRoute,
  AuthNotFoundRoute: AuthNotFoundRoute,
  AuthReportsRoute: AuthReportsRoute,
  AuthSelloutRoute: AuthSelloutRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
