/**
 * Message codes for API responses.
 * These codes can be used by the frontend to map to appropriate translations.
 */

// General
const MESSAGE_GENERAL = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

// Auth
const MESSAGE_AUTH = {
  AUTH_HEADER_REQUIRED: 'AUTH_HEADER_REQUIRED',
  AUTH_HEADER_PARSE_ERROR: 'AUTH_HEADER_PARSE_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_DESTROYED: 'SESSION_DESTROYED',
  SESSION_CREATION_FAILED: 'SESSION_CREATION_FAILED',
  SESSION_CREATED: 'SESSION_CREATED',
} as const

// Users
const MESSAGE_USERS = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_NO_SESSION: 'USER_NO_SESSION',
  USER_ALREADY_ACTIVE: 'USER_ALREADY_ACTIVE',
  USER_ALREADY_DISABLED: 'USER_ALREADY_DISABLED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_DISABLED: 'USER_DISABLED',
  USER_CREATED: 'USER_CREATED',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_PENDING: 'USER_PENDING',
  USER_NOT_PENDING: 'USER_NOT_PENDING',
  USER_CANNOT_DISABLE_SELF: 'USER_CANNOT_DISABLE_SELF',
  USER_JOINED: 'USER_JOINED',
  ACCESS_REQUESTED: 'ACCESS_REQUESTED',
} as const

// Books (Example)
const MESSAGE_BOOKS = {
  BOOK_NOT_FOUND: 'BOOK_NOT_FOUND',
  BOOK_CREATED: 'BOOK_CREATED',
  BOOK_UPDATED: 'BOOK_UPDATED',
  BOOK_DELETED: 'BOOK_DELETED',
  BOOK_ISBN_EXISTS: 'BOOK_ISBN_EXISTS',
} as const

// Book Reviews (Example)
const MESSAGE_REVIEWS = {
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  REVIEW_CREATED: 'REVIEW_CREATED',
  REVIEW_UPDATED: 'REVIEW_UPDATED',
  REVIEW_DELETED: 'REVIEW_DELETED',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  REVIEW_INVALID_RATING: 'REVIEW_INVALID_RATING',
} as const

// Clients (Example)
const MESSAGE_CLIENTS = {
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  CLIENT_CREATED: 'CLIENT_CREATED',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  COMMENT_CREATED: 'COMMENT_CREATED',
  COMMENT_UPDATED: 'COMMENT_UPDATED',
  COMMENT_DELETED: 'COMMENT_DELETED',
} as const

// PDF Parsing
const MESSAGE_PDF = {
  PDF_FILE_REQUIRED: 'PDF_FILE_REQUIRED',
  PDF_FILE_TOO_LARGE: 'PDF_FILE_TOO_LARGE',
  PDF_INVALID_FILE_TYPE: 'PDF_INVALID_FILE_TYPE',
  PDF_NO_TEXT_CONTENT: 'PDF_NO_TEXT_CONTENT',
  PDF_PARSE_FAILED: 'PDF_PARSE_FAILED',
} as const

// Merged MESSAGE object
export const MESSAGE = {
  ...MESSAGE_GENERAL,
  ...MESSAGE_AUTH,
  ...MESSAGE_USERS,
  ...MESSAGE_BOOKS,
  ...MESSAGE_REVIEWS,
  ...MESSAGE_CLIENTS,
  ...MESSAGE_PDF,
} as const

export type Message = (typeof MESSAGE)[keyof typeof MESSAGE]
