/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchenSinkRouteImport } from './routes/kitchen-sink'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthDispatchRouteImport } from './routes/_auth/dispatch'
import { Route as AuthSplatRouteImport } from './routes/_auth/$'
import { Route as AuthDispatchIndexRouteImport } from './routes/_auth/dispatch/index'
import { Route as AuthDispatchJobIdRouteImport } from './routes/_auth/dispatch/$jobId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenSinkRoute = KitchenSinkRouteImport.update({
  id: '/kitchen-sink',
  path: '/kitchen-sink',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDispatchRoute = AuthDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDispatchIndexRoute = AuthDispatchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDispatchRoute,
} as any)
const AuthDispatchJobIdRoute = AuthDispatchJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AuthDispatchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/callback': typeof CallbackRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/login': typeof LoginRoute
  '/$': typeof AuthSplatRoute
  '/dispatch': typeof AuthDispatchRouteWithChildren
  '/': typeof AuthIndexRoute
  '/dispatch/$jobId': typeof AuthDispatchJobIdRoute
  '/dispatch/': typeof AuthDispatchIndexRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/login': typeof LoginRoute
  '/$': typeof AuthSplatRoute
  '/': typeof AuthIndexRoute
  '/dispatch/$jobId': typeof AuthDispatchJobIdRoute
  '/dispatch': typeof AuthDispatchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/callback': typeof CallbackRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/login': typeof LoginRoute
  '/_auth/$': typeof AuthSplatRoute
  '/_auth/dispatch': typeof AuthDispatchRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/dispatch/$jobId': typeof AuthDispatchJobIdRoute
  '/_auth/dispatch/': typeof AuthDispatchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/callback'
    | '/kitchen-sink'
    | '/login'
    | '/$'
    | '/dispatch'
    | '/'
    | '/dispatch/$jobId'
    | '/dispatch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/kitchen-sink'
    | '/login'
    | '/$'
    | '/'
    | '/dispatch/$jobId'
    | '/dispatch'
  id:
    | '__root__'
    | '/_auth'
    | '/callback'
    | '/kitchen-sink'
    | '/login'
    | '/_auth/$'
    | '/_auth/dispatch'
    | '/_auth/'
    | '/_auth/dispatch/$jobId'
    | '/_auth/dispatch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  KitchenSinkRoute: typeof KitchenSinkRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-sink': {
      id: '/kitchen-sink'
      path: '/kitchen-sink'
      fullPath: '/kitchen-sink'
      preLoaderRoute: typeof KitchenSinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dispatch': {
      id: '/_auth/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AuthDispatchRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/$': {
      id: '/_auth/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dispatch/': {
      id: '/_auth/dispatch/'
      path: '/'
      fullPath: '/dispatch/'
      preLoaderRoute: typeof AuthDispatchIndexRouteImport
      parentRoute: typeof AuthDispatchRoute
    }
    '/_auth/dispatch/$jobId': {
      id: '/_auth/dispatch/$jobId'
      path: '/$jobId'
      fullPath: '/dispatch/$jobId'
      preLoaderRoute: typeof AuthDispatchJobIdRouteImport
      parentRoute: typeof AuthDispatchRoute
    }
  }
}

interface AuthDispatchRouteChildren {
  AuthDispatchJobIdRoute: typeof AuthDispatchJobIdRoute
  AuthDispatchIndexRoute: typeof AuthDispatchIndexRoute
}

const AuthDispatchRouteChildren: AuthDispatchRouteChildren = {
  AuthDispatchJobIdRoute: AuthDispatchJobIdRoute,
  AuthDispatchIndexRoute: AuthDispatchIndexRoute,
}

const AuthDispatchRouteWithChildren = AuthDispatchRoute._addFileChildren(
  AuthDispatchRouteChildren,
)

interface AuthRouteChildren {
  AuthSplatRoute: typeof AuthSplatRoute
  AuthDispatchRoute: typeof AuthDispatchRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSplatRoute: AuthSplatRoute,
  AuthDispatchRoute: AuthDispatchRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  CallbackRoute: CallbackRoute,
  KitchenSinkRoute: KitchenSinkRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
